import { GalleryItem } from '@/types/gallery';

export const INITIAL_GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'gal-001',
    title: 'Kajian Subuh Ahad Berjamaah & Sarapan Bersama',
    caption: 'Antusiasme jamaah BTP Blok AE dalam menyimak materi Fiqih Muamalah praktis di ruang sholat utama.',
    category: 'KAJIAN',
    photoUrl: 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?auto=format&fit=crop&w=1000&q=80',
    division: 'Seksi Peribadatan & Dakwah',
    uploadedBy: 'Drs. Manai, M.M.',
    date: '2026-09-06',
  },
  {
    id: 'gal-002',
    title: 'Peringatan Isra Mi\'raj & Santunan 48 Keluarga Dhuafa',
    caption: 'Penyaluran beras lumbung dan santunan biaya pendidikan untuk anak yatim berprestasi.',
    category: 'PHBI',
    photoUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?auto=format&fit=crop&w=1000&q=80',
    division: 'Seksi PHBI & Hari Besar Islam',
    uploadedBy: 'Muh. Ilham, S.Kom.',
    date: '2026-08-25',
  },
  {
    id: 'gal-003',
    title: 'Rapat Kerja Pengurus DKM & Pleno 74 Program Kerja',
    caption: 'Musyawarah penyusunan matriks program kerja 4 pilar di hadapan Dewan Pengawas dan perwakilan 5 RT.',
    category: 'RAPAT',
    photoUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1000&q=80',
    division: 'Sekretariat DKM',
    uploadedBy: 'Muh. Ilham, S.Kom.',
    date: '2026-08-15',
  },
  {
    id: 'gal-004',
    title: 'Penyaluran Beras Lumbung Mandiri Serambi Masjid',
    caption: 'Pelayanan dispenser lumbung beras mandiri bagi warga lansia dan mustahiq tanpa birokrasi rumit.',
    category: 'SOSIAL',
    photoUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=1000&q=80',
    division: 'Seksi ZISWAF & Kesejahteraan Umat',
    uploadedBy: 'H. Sahali, S.E.',
    date: '2026-09-02',
  },
  {
    id: 'gal-005',
    title: 'Pemasangan Mahkota Kubah Menara 30 Meter',
    caption: 'Proses perakitan struktur baja mahkota menara utama oleh tim vendor dan pengawasan tim Sarpras.',
    category: 'PEMBANGUNAN',
    photoUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?auto=format&fit=crop&w=1000&q=80',
    division: 'Seksi Sarana & Prasarana',
    uploadedBy: 'Dr. Ir. H. Ruslan, M.T.',
    date: '2026-08-28',
  },
  {
    id: 'gal-006',
    title: 'Ujian Munaqasyah & Wisuda Tahsin Santri TPA',
    caption: '65 santri TPA Babul Khaer mengikuti evaluasi hafalan juz 30 dan adab harian dengan didampingi orang tua.',
    category: 'TPA',
    photoUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1000&q=80',
    division: 'Unit Pendidikan Al-Qur\'an (TPA)',
    uploadedBy: 'Drs. Manai, M.M.',
    date: '2026-08-10',
  },
];
