import { IntegratedMeeting } from '@/types/meeting';

export const INITIAL_INTEGRATED_MEETINGS: IntegratedMeeting[] = [
  {
    id: 'mtg-001',
    title: 'Rapat Pleno DKM: Evaluasi Idul Adha & Persiapan Agenda PHBI Semester II',
    meetingType: 'PLENO',
    date: '2026-08-24',
    startTime: '20:00',
    endTime: '22:30',
    location: 'Serambi Utama Masjid Babul Khaer BTP Blok AE',
    agenda: [
      'Pembacaan Laporan Realisasi Keuangan Idul Adha 1447 H',
      'Pengalihan Saldo Surplus Qurban Rp 4.250.000 ke Kas Operasional',
      'Penyusunan Jadwal Servis AC Duduk & Pembersihan Filter Sound System',
      'Pembentukan Panitia Maulid Nabi Muhammad SAW 1448 H Satu Pintu',
    ],
    invitees: [
      { id: 'inv-1', userId: 'usr-ketua', name: 'H. Arifin, S.E.', role: 'Ketua Umum DKM', status: 'HADIR' },
      { id: 'inv-2', userId: 'usr-sekretaris', name: 'Ahmad Fauzi, S.Kom.', role: 'Sekretaris Umum', status: 'HADIR' },
      { id: 'inv-3', userId: 'usr-bendahara', name: 'H. Sahali', role: 'Bendahara Umum', status: 'HADIR' },
      { id: 'inv-4', userId: 'usr-sarpras', name: 'Bambang Sudarmono, S.T.', role: 'Koordinator Sarpras', status: 'HADIR' },
      { id: 'inv-5', userId: 'usr-kemasjidan', name: 'Drs. Manai, M.M.', role: 'Koordinator Dakwah & Ibadah', status: 'HADIR' },
      { id: 'inv-6', userId: 'usr-pengawas', name: 'Drs. H. Muh. Natsir, M.Si.', role: 'Dewan Pengawas DKM', status: 'HADIR' },
      { id: 'inv-7', name: 'Ust. Haris, S.Pd.I', role: 'Imam Rawatib & Seksi Dakwah', status: 'HADIR' },
      { id: 'inv-8', name: 'Hj. Rosdiana', role: 'Koordinator Majelis Taklim Muslimah', status: 'IZIN', notes: 'Menghadiri acara keluarga' },
      { id: 'inv-9', name: 'Ketua RW 08', role: 'Tokoh Masyarakat', status: 'HADIR' },
    ],
    externalInvitees: ['Ketua RW 08 BTP', 'Ketua RT 01-05'],
    minutes: {
      summary: 'Rapat pleno dibuka oleh Ketua Umum H. Arifin pada pukul 20.00 WITA. Pembahasan difokuskan pada pertanggungjawaban qurban dan tertib keuangan satu pintu menjelang peringatan Maulid Nabi 1448 H.',
      decisions: [
        'Laporan Keuangan Qurban disahkan secara bulat dengan surplus kas Rp 4.250.000.',
        'Seluruh proposal donasi kegiatan PHBI Maulid wajib diterbitkan satu pintu melalui bendahara.',
        'Pemberian tugas teknis servis AC Daikin kepada Seksi Sarpras sebelum 10 September 2026.',
      ],
      actionItems: [
        {
          id: 'act-101',
          task: 'Menerbitkan surat undangan pembentukan panitia Maulid Nabi ke perwakilan lorong',
          pic: 'Ahmad Fauzi (Sekretaris Umum)',
          deadline: '2026-09-05',
          priority: 'HIGH',
          status: 'COMPLETED',
        },
        {
          id: 'act-102',
          task: 'Panggilan teknisi pendingin untuk servis berkala 6 unit AC duduk Daikin',
          pic: 'Bambang Sudarmono (Sarpras)',
          deadline: '2026-09-08',
          priority: 'HIGH',
          status: 'IN_PROGRESS',
        },
        {
          id: 'act-103',
          task: 'Penyusunan estimasi rincian anggaran konsumsi Maulid Nabi',
          pic: 'H. Sahali (Bendahara)',
          deadline: '2026-09-11',
          priority: 'MEDIUM',
          status: 'PENDING',
        },
      ],
      recordedBy: 'Ahmad Fauzi, S.Kom. (Sekretaris Umum)',
      finalizedAt: '2026-08-25T08:30:00.000Z',
    },
    status: 'SELESAI',
    createdAt: '2026-08-20T10:00:00.000Z',
  },
  {
    id: 'mtg-002',
    title: 'Rapat Koordinasi Persiapan Maulid Nabi & Penertiban Parkir Lorong',
    meetingType: 'KOORDINASI_SEKSI',
    date: '2026-09-12',
    startTime: '20:00',
    endTime: '22:00',
    location: 'Ruang Rapat Sekretariat DKM Babul Khaer',
    agenda: [
      'Laporan kesiapan penceramah utama Maulid Nabi 1448 H',
      'Koordinasi teknis penutupan lorong parkir bersama Satpam RW 08',
      'Penyusunan daftar penerima paket bingkisan berkah maulid',
    ],
    invitees: [
      { id: 'inv-201', userId: 'usr-ketua', name: 'H. Arifin, S.E.', role: 'Ketua Umum DKM', status: 'UNDANGAN' },
      { id: 'inv-202', userId: 'usr-sekretaris', name: 'Ahmad Fauzi, S.Kom.', role: 'Sekretaris Umum', status: 'UNDANGAN' },
      { id: 'inv-203', userId: 'usr-bendahara', name: 'H. Sahali', role: 'Bendahara Umum', status: 'UNDANGAN' },
      { id: 'inv-204', userId: 'usr-kemasjidan', name: 'Drs. Manai, M.M.', role: 'Koordinator Dakwah', status: 'UNDANGAN' },
      { id: 'inv-205', name: 'Koordinator Keamanan & Satpam', role: 'Seksi Keamanan Lingkungan', status: 'UNDANGAN' },
      { id: 'inv-206', name: 'Ketua IRMA Babul Khaer', role: 'Perwakilan Pemuda', status: 'UNDANGAN' },
    ],
    externalInvitees: ['Satpam RW 08', 'Babinsa Tamalanrea'],
    minutes: {
      summary: '',
      decisions: [],
      actionItems: [],
      recordedBy: 'Sekretaris Rapat',
    },
    status: 'TERJADWAL',
    createdAt: '2026-09-04T12:00:00.000Z',
  },
];
