import { PhysicalProjectItem } from '@/types/project';

export const INITIAL_PHYSICAL_PROJECTS: PhysicalProjectItem[] = [
  {
    id: 'prj-001',
    code: 'PRJ-2026-001',
    title: 'Renovasi Plafon & Penanganan Atap Bocor Lantai 2',
    category: 'RENOVASI',
    allocatedBudget: 350000000, // Rp 350 Juta Pagu Raker
    realizedBudget: 145000000,
    progressPercentage: 55,
    status: 'DALAM_PENGERJAAN',
    urgencyLevel: 'MENDESAK',
    responsiblePerson: 'Faisal T. Parussengi, S.S. (Koord. Sarpras)',
    contractorVendor: 'CV. Biringkanaya Konstruksi Mandiri',
    startDate: '2026-08-15',
    targetEndDate: '2026-11-30',
    description: 'Penggantian menyeluruh rangka plafon gipsum tahan air ruang sholat utama lantai 2 akibat kerusakan kebocoran atap saat musim hujan. Prioritas paling mendesak hasil Rapat Kerja Komisi II.',
    milestones: [
      { id: 'm1', title: 'Audit titik rembesan & uji coba semprot air atap dak', isDone: true, targetDate: '2026-08-20' },
      { id: 'm2', title: 'Pembongkaran plafon lama yang lapuk & pembersihan puing', isDone: true, targetDate: '2026-08-30' },
      { id: 'm3', title: 'Pemasangan lapisan membrane waterproofing anti bocor 3 lapis', isDone: true, targetDate: '2026-09-05' },
      { id: 'm4', title: 'Pemasangan rangka hollow galvanis anti karat', isDone: false, targetDate: '2026-09-25' },
      { id: 'm5', title: 'Pemasangan papan gypsum water-resistant & pengecatan akhir', isDone: false, targetDate: '2026-10-30' },
      { id: 'm6', title: 'Uji serah terima & inspeksi Dewan Pengawas DKM', isDone: false, targetDate: '2026-11-15' },
    ],
    notes: 'Pekerjaan fisik dilakukan pada hari kerja ba\'da Ashar s/d pukul 22.00 agar tidak mengganggu ketertiban sholat jamaah.',
    photos: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb186156f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop&q=80',
    ],
    updatedAt: '2026-09-05T14:30:00.000Z',
  },
  {
    id: 'prj-002',
    code: 'PRJ-2026-002',
    title: 'Pembangunan Menara Masjid 30 Meter',
    category: 'PEMBANGUNAN_BARU',
    allocatedBudget: 1550000000, // Rp 1.55 Milyar Pagu Raker
    realizedBudget: 420000000,
    progressPercentage: 30,
    status: 'DALAM_PENGERJAAN',
    urgencyLevel: 'TINGGI',
    responsiblePerson: 'Ir. Muhammad Natsir, S.T. & Panitia Pembangunan',
    contractorVendor: 'PT. Pilar Karya Sulsel',
    startDate: '2026-06-01',
    targetEndDate: '2027-03-31',
    description: 'Pembangunan menara masjid permanen setinggi 30 meter sebagai landmark kemakmuran Masjid Babul Khaer dan penempatan corong horn speaker azan jangkauan luas Blok AE hingga perbatasan BTP.',
    milestones: [
      { id: 'm1', title: 'Penyusunan gambar DED arsitektur & perhitungan struktur tiang pancang', isDone: true, targetDate: '2026-06-15' },
      { id: 'm2', title: 'Pengeboran soil test & pondasi cakar ayam bor pile 12 titik', isDone: true, targetDate: '2026-07-20' },
      { id: 'm3', title: 'Pengecoran kolom struktur utama beton bertulang lantai dasar s.d 10m', isDone: true, targetDate: '2026-08-30' },
      { id: 'm4', title: 'Pekerjaan struktur elevated lantai 11m s.d 20m', isDone: false, targetDate: '2026-10-30' },
      { id: 'm5', title: 'Pemasangan kubah mini menara stainless & penangkal petir elektrostatis', isDone: false, targetDate: '2026-12-20' },
      { id: 'm6', title: 'Pemasangan instalasi sound horn TOA 8 unit & lampu hias sorot', isDone: false, targetDate: '2027-02-15' },
    ],
    notes: 'Didanai melalui pos khusus Panitia Pembangunan & Donatur Wakaf Menara (rekening satu pintu).',
    photos: [
      'https://images.unsplash.com/photo-1590076215667-875d4ef2d7ee?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=800&auto=format&fit=crop&q=80',
    ],
    updatedAt: '2026-09-04T10:15:00.000Z',
  },
  {
    id: 'prj-003',
    code: 'PRJ-2026-003',
    title: 'Perbaikan Drainase & Pembuangan Air Hujan',
    category: 'PERBAIKAN_INFRASTRUKTUR',
    allocatedBudget: 150000000, // Rp 150 Juta Pagu Raker
    realizedBudget: 105000000,
    progressPercentage: 70,
    status: 'DALAM_PENGERJAAN',
    urgencyLevel: 'TINGGI',
    responsiblePerson: 'H. Muh. Nancha Pattanang, S.E. (Ketua II)',
    contractorVendor: 'Swakelola DKM & Warga RT 01-05',
    startDate: '2026-07-10',
    targetEndDate: '2026-10-15',
    description: 'Pelebaran dan pemasangan u-ditch beton saluran pembuangan air keliling masjid untuk meniadakan genangan air di pelataran serambi dan area parkir jamaah saat musim penghujan.',
    milestones: [
      { id: 'm1', title: 'Pengukuran kontur kemiringan elevasi pembuangan ke parit utama', isDone: true, targetDate: '2026-07-15' },
      { id: 'm2', title: 'Penggalian parit lama & pengadaan u-ditch beton bertulang 40x40cm', isDone: true, targetDate: '2026-08-10' },
      { id: 'm3', title: 'Pemasangan pipa buangan dari talang atap dak ke bak kontrol', isDone: true, targetDate: '2026-08-25' },
      { id: 'm4', title: 'Pengecoran plat penutup grill besi jalan masuk parkir', isDone: false, targetDate: '2026-09-30' },
    ],
    notes: 'Progres sangat lancar, gotong royong warga setiap hari Ahad pagi.',
    updatedAt: '2026-09-05T09:00:00.000Z',
  },
  {
    id: 'prj-004',
    code: 'PRJ-2026-004',
    title: 'Pengadaan AC Duduk Daikin Standing Floor 5 PK',
    category: 'PENGADAAN_SARPRAS',
    allocatedBudget: 27000000, // Rp 27 Juta Pagu Raker
    realizedBudget: 27000000,
    progressPercentage: 100,
    status: 'SELESAI',
    urgencyLevel: 'TINGGI',
    responsiblePerson: 'Faisal T. Parussengi, S.S.',
    contractorVendor: 'CV. Sejuk Abadi Makassar',
    startDate: '2026-08-01',
    targetEndDate: '2026-08-10',
    description: 'Pengadaan dan instalasi 1 unit AC Standing Daikin 5 PK baru di saf utama depan imam masjid. Berfungsi normal untuk mendinginkan ruang sholat utama saat sholat Jumat dan pengajian akbar.',
    milestones: [
      { id: 'm1', title: 'Survei daya listrik PLN & penentuan posisi instalasi', isDone: true, targetDate: '2026-08-02' },
      { id: 'm2', title: 'Pembelian unit AC Daikin 5 PK R32 Inverter', isDone: true, targetDate: '2026-08-05' },
      { id: 'm3', title: 'Instalasi pipa tembaga, kabel power & outdoor bracket', isDone: true, targetDate: '2026-08-08' },
      { id: 'm4', title: 'Testing suhu dingin & serah terima operasional', isDone: true, targetDate: '2026-08-10' },
    ],
    notes: 'Selesai 100%. Telah masuk ke buku aset inventaris kode AST-AC-001.',
    updatedAt: '2026-08-10T16:00:00.000Z',
  },
  {
    id: 'prj-005',
    code: 'PRJ-2026-005',
    title: 'Relokasi & Modul Otomatis Genset 15 KVA',
    category: 'RENOVASI',
    allocatedBudget: 3500000, // Rp 3.5 Juta Pagu Raker
    realizedBudget: 3500000,
    progressPercentage: 100,
    status: 'SELESAI',
    urgencyLevel: 'MENDESAK',
    responsiblePerson: 'Faisal T. Parussengi & Marbot Firman',
    contractorVendor: 'Teknisi Listrik BTP',
    startDate: '2026-08-20',
    targetEndDate: '2026-08-28',
    description: 'Pemasangan modul otomatis ATS (Automatic Transfer Switch) dan pemindahan unit genset diesel 15 KVA ke bilik genset samping agar genset menyala otomatis dalam tempo 5 detik saat pemadaman PLN tiba-tiba.',
    milestones: [
      { id: 'm1', title: 'Pembuatan dudukan cor peredam getaran genset di bilik samping', isDone: true, targetDate: '2026-08-22' },
      { id: 'm2', title: 'Perakitan panel ATS & kontaktor otomatis magnetik', isDone: true, targetDate: '2026-08-25' },
      { id: 'm3', title: 'Uji coba simulasi pemadaman listrik PLN 3x', isDone: true, targetDate: '2026-08-28' },
    ],
    notes: 'Selesai 100%. Genset kini otomatis menyala saat mati lampu tanpa harus ditarik manual.',
    updatedAt: '2026-08-28T17:00:00.000Z',
  },
];
