import { ApprovalItem, FieldKPI } from '@/types/reports';

export const INITIAL_APPROVALS: ApprovalItem[] = [
  {
    id: 'appr-001',
    type: 'PENCAIRAN_DANA',
    title: 'Pencairan Dana Operasional: Pemeliharaan Servis Genset Honda EU70is',
    referenceNumber: 'DISP-2026-09-001',
    category: 'Sarana Prasarana',
    submittedBy: 'Faisal T. Parussengi, S.S.',
    submittedRole: 'Koordinator Sarpras',
    submittedAt: '2026-09-03T10:30:00.000Z',
    amount: 850000,
    description: 'Biaya penggantian oli mesin 10W-30, filter bensin, dan modul otomatis genset hasil rekomendasi Raker 2026.',
    status: 'MENUNGGU_VERIFIKASI',
  },
  {
    id: 'appr-002',
    type: 'SURAT_KELUAR',
    title: 'Pengesahan Surat Resmi: Undangan Rapat Pleno Persiapan Maulid Nabi 1448 H',
    referenceNumber: '042/DKM-MBH/UND/IX/2026',
    category: 'Kesekretariatan',
    submittedBy: 'Ir. Muhammad Natsir, S.T.',
    submittedRole: 'Sekretaris Umum',
    submittedAt: '2026-09-04T08:15:00.000Z',
    description: 'Surat undangan resmi musyawarah persiapan Maulid Nabi untuk tokoh masyarakat, Ketua RT 01-05 Blok AE, dan Majelis Taklim.',
    status: 'MENUNGGU_VERIFIKASI',
  },
  {
    id: 'appr-003',
    type: 'PENCAIRAN_DANA',
    title: 'Pencairan Dana Swadaya PHBI Satu Pintu: Uang Muka Tenda & Konsumsi Peringatan Maulid',
    referenceNumber: 'DISP-2026-09-002',
    category: 'Swadaya PHBI',
    submittedBy: 'H. Lukman Hakim',
    submittedRole: 'Ketua Panitia PHBI',
    submittedAt: '2026-09-04T09:00:00.000Z',
    amount: 3500000,
    description: 'Pencairan uang muka vendor tenda kanopi serambi masjid dan konsumsi penceramah/tamu undangan dari pos swadaya satu pintu.',
    status: 'MENUNGGU_VERIFIKASI',
  },
  {
    id: 'appr-004',
    type: 'PENCAIRAN_DANA',
    title: 'Penyaluran ZISWAF Darurat: Bantuan Medis & Sembako Ibu Aminah (RT 02)',
    referenceNumber: 'DISP-2026-09-003',
    category: 'ZISWAF & Mustahiq',
    submittedBy: 'Drs. H. Muh. Rusdi Lahajji, M. Pd.',
    submittedRole: 'Koordinator Humas & Sosial',
    submittedAt: '2026-09-02T14:20:00.000Z',
    amount: 600000,
    description: 'Penyaluran dana zakat mal/santunan darurat mustahiq lansia dhuafa warga RT 02 Blok AE yang sakit.',
    status: 'DISETUJUI',
    dispositionNotes: 'Disetujui untuk dicairkan segera melalui kas ZISWAF. Semoga lekas sembuh dan bermanfaat.',
    verifiedBy: 'Drs. Muhammad Hasri, M. Hum. (Ketua Umum)',
    verifiedAt: '2026-09-02T16:00:00.000Z',
  },
  {
    id: 'appr-005',
    type: 'PENGADAAN_SARPRAS',
    title: 'Pengajuan Pengadaan 2 Unit Mikrofon Nirkabel Tambahan',
    referenceNumber: 'DISP-2026-08-019',
    category: 'Sarana Prasarana',
    submittedBy: 'Faisal T. Parussengi, S.S.',
    submittedRole: 'Koordinator Sarpras',
    submittedAt: '2026-08-28T11:00:00.000Z',
    amount: 3800000,
    description: 'Pengadaan mic handheld baru untuk ruang serambi akhwat dan imam rawatib.',
    status: 'PERLU_REVISI',
    dispositionNotes: 'Mohon dicek kembali apakah spool mic Shure yang ada di ruang operator sound masih dapat diservis di teknisi BTP sebelum memutuskan beli baru.',
    verifiedBy: 'Drs. Muhammad Hasri, M. Hum. (Ketua Umum)',
    verifiedAt: '2026-08-29T09:30:00.000Z',
  },
];

export const INITIAL_FIELD_KPIS: FieldKPI[] = [
  {
    field: 'KESEKRETARIATAN',
    title: 'Bidang I: Tata Usaha & Kesekretariatan',
    leaderName: 'Ir. Muhammad Natsir, S.T. (Sekretaris Umum)',
    score: 94,
    status: 'SANGAT_BAIK',
    summary: 'Administrasi persuratan berjalan tertib dengan nomor otomatis Spreadsheets, e-arsip digital teratur, dan notulensi rapat terekstraksi cepat.',
    indicators: [
      { label: 'Surat Terarsip Digital', current: 15, target: 15, percent: 100, unit: 'Surat' },
      { label: 'Ketepatan Penomoran Otomatis', current: 100, target: 100, percent: 100, unit: '%' },
      { label: 'Penyelesaian Tugas Rapat Pleno', current: 82, target: 80, percent: 102, unit: '%' },
      { label: 'Rata-rata Waktu Respons Draf Surat', current: 1.5, target: 3, percent: 100, unit: 'Jam' },
    ],
    keyNotes: [
      'Implementasi kop surat resmi A4 mempermudah korespondensi dengan Kemenag dan Kelurahan Tamalanrea.',
      'Daftar tugas rapat (Action Items) terpantau langsung oleh penanggung jawab.',
    ],
  },
  {
    field: 'KEMASJIDAN_JAMAAH',
    title: 'Bidang II: Peribadatan & Dakwah (Supervisi Ketua I)',
    leaderName: 'Drs. Manai, M.M. / Drs. H. Suardi, M.Pd.',
    score: 89,
    status: 'BAIK',
    summary: 'Cakupan pendataan warga BTP Blok AE RT 01-05 meningkat signifikan; pemetaan mustahiq zakat darurat sangat responsif.',
    indicators: [
      { label: 'Cakupan Sensus Warga Blok AE', current: 87, target: 95, percent: 91, unit: '%' },
      { label: 'Validasi Data Mustahiq & Dhuafa', current: 100, target: 100, percent: 100, unit: '%' },
      { label: 'Partisipasi Remaja Masjid (IRMBH)', current: 28, target: 30, percent: 93, unit: 'Kader' },
      { label: 'Rasio Pelayanan Bantuan Sosial', current: 100, target: 100, percent: 100, unit: '%' },
    ],
    keyNotes: [
      'Basis data kependudukan telah memiliki kontak WhatsApp aktif untuk kemudahan penyebaran undangan taklim.',
      'Sistem filter mustahiq meminimalisir salah sasaran dalam penyaluran beras zakat fitrah dan sembako.',
    ],
  },
  {
    field: 'KEUANGAN_PERBENDAHARAAN',
    title: 'Bidang III: Keuangan & Perbendaharaan',
    leaderName: 'H. Sahali (Bendahara Umum)',
    score: 93,
    status: 'SANGAT_BAIK',
    summary: 'Pemisahan tegas pos kas berhasil diterapkan. Dana Swadaya PHBI satu pintu mencegah tumpang tindih anggaran operasional rutin.',
    indicators: [
      { label: 'Kepatuhan Pemisahan Pos PHBI', current: 100, target: 100, percent: 100, unit: '%' },
      { label: 'Ketertiban Pencatatan Kas Masuk/Keluar', current: 100, target: 100, percent: 100, unit: '%' },
      { label: 'Rasio Cadangan Kas Minimum', current: 3.8, target: 2.0, percent: 190, unit: 'Bulan Ops' },
      { label: 'Publikasi Saldo Kotak Amal Jumat', current: 100, target: 100, percent: 100, unit: '%' },
    ],
    keyNotes: [
      'Saldo kas operasional dan PHBI selalu siap diaudit oleh Badan Pengawas DKM.',
      'Ekspor buku kas ke spreadsheet Excel memudahkan penyusunan laporan mingguan shalat Jumat.',
    ],
  },
  {
    field: 'SARANA_PRASARANA',
    title: 'Bidang IV: Pemeliharaan Sarana & Prasarana (Supervisi Ketua II)',
    leaderName: 'Faisal T. Parussengi, S.S. / H. Muh. Nancha Pattanang, S.E.',
    score: 84,
    status: 'BAIK',
    summary: 'Kondisi fisik aset ibadah terjaga baik. Pengingat berkala servis AC duduk per 3 bulan dan genset silent berjalan proaktif.',
    indicators: [
      { label: 'Kesiapan Sarana Ibadah Prima', current: 87.5, target: 90, percent: 97, unit: '%' },
      { label: 'Kepatuhan Siklus Servis AC Duduk', current: 85, target: 100, percent: 85, unit: '%' },
      { label: 'Kesiapsiagaan Genset Listrik', current: 100, target: 100, percent: 100, unit: '%' },
      { label: 'Kondisi Akustik & Sound System', current: 80, target: 95, percent: 84, unit: '%' },
    ],
    keyNotes: [
      'AC Duduk Daikin ruang utama masjid dijadwalkan servis rutin berkala teknisi resmi.',
      'Perbaikan spool mikrofon nirkabel 2 sedang diajukan agar tidak menimbulkan desis saat kajian.',
    ],
  },
];
