import { User, UserRole, RolePermission, AuditLogEntry } from '@/types/auth';

export const OFFICIAL_USERS: User[] = [
  {
    id: 'usr-ketua',
    name: 'Drs. H. M. Said, M.Pd.',
    title: 'Ketua Umum DKM',
    role: 'KETUA_UMUM',
    roleLabel: 'Ketua Umum DKM',
    email: 'ketua@babulkhaer.or.id',
    phone: '0812-4112-9901',
    department: 'Badan Pimpinan Harian (Eksekutif)',
    isReadOnly: false,
    pin: '123456',
    bio: 'Pimpinan tertinggi operasional DKM Babul Khaer BTP Blok AE periode 2026-2029. Pemegang hak otorisasi dan disposisi satu pintu pengesahan surat dinas dan pencairan kas perbendaharaan.',
  },
  {
    id: 'usr-sekretaris',
    name: 'M. Yusuf, S.Ag.',
    title: 'Sekretaris Umum DKM',
    role: 'SEKRETARIS',
    roleLabel: 'Sekretaris Umum',
    email: 'sekretaris@babulkhaer.or.id',
    phone: '0813-5521-8842',
    department: 'Bidang Kesekretariatan & Tata Usaha',
    isReadOnly: false,
    pin: '123456',
    bio: 'Penanggung jawab administrasi umum, tata persuratan dinas resmi, e-arsip berkas digital, dan ekstraksi notulensi rapat pleno AI DKM.',
  },
  {
    id: 'usr-bendahara',
    name: 'H. Abdul Rahman, S.E.',
    title: 'Bendahara Umum DKM',
    role: 'BENDAHARA',
    roleLabel: 'Bendahara Umum',
    email: 'bendahara@babulkhaer.or.id',
    phone: '0852-9934-7711',
    department: 'Bidang Keuangan & Perbendaharaan',
    isReadOnly: false,
    pin: '123456',
    bio: 'Pengelola kas operasional harian, pemisahan pos dana swadaya jamaah PHBI satu pintu, penerimaan ZISWAF, dan laporan realisasi cashflow.',
  },
  {
    id: 'usr-sarpras',
    name: 'Bpk. Irwan Syarifuddin',
    title: 'Koordinator Sarana & Prasarana',
    role: 'SARPRAS',
    roleLabel: 'Koordinator Sarpras',
    email: 'sarpras@babulkhaer.or.id',
    phone: '0821-8876-5533',
    department: 'Bidang Sarana & Prasarana Fisik',
    isReadOnly: false,
    pin: '123456',
    bio: 'Penanggung jawab kelayakan fasilitas fisik masjid, inventarisasi AC Daikin, genset cadangan, sound system utama, dan jadwal servis berkala.',
  },
  {
    id: 'usr-kemasjidan',
    name: 'Ust. H. Syamsuddin, Lc.',
    title: 'Bidang Dakwah & Kemasjidan',
    role: 'KEMASJIDAN',
    roleLabel: 'Kemasjidan & Dakwah',
    email: 'kemasjidan@babulkhaer.or.id',
    phone: '0812-7788-3321',
    department: 'Bidang Kemasjidan, Dakwah & Jamaah',
    isReadOnly: false,
    pin: '123456',
    bio: 'Penanggung jawab sensus jamaah RT 01-05 BTP Blok AE, pendataan mustahiq zakat dan penyaluran bansos dhuafa, serta impor data Excel massal.',
  },
  {
    id: 'usr-pengawas',
    name: 'H. M. Arsyad',
    title: 'Dewan Penasehat & Pengawas',
    role: 'DEWAN_PENGAWAS',
    roleLabel: 'Dewan Penasehat / Pengawas',
    email: 'pengawas@babulkhaer.or.id',
    phone: '0811-4433-2211',
    department: 'Badan Pengawas & Penasehat Syariah',
    isReadOnly: true,
    pin: '123456',
    bio: 'Pengawas independen jalannya amanah kepengurusan DKM Babul Khaer sesuai AD/ART MBH 2020. Memiliki hak akses khusus Read-Only untuk evaluasi KPI 4 pilar dan inspeksi log audit aktivitas.',
  },
];

export const ROLE_PERMISSIONS: Record<UserRole, RolePermission> = {
  KETUA_UMUM: {
    canAccessArchive: true,
    canCreateLetter: true,
    canAccessMinutes: true,
    canAccessJamaah: true,
    canMutateJamaah: true,
    canAccessFinance: true,
    canMutateFinance: true,
    canAccessAssets: true,
    canMutateAssets: true,
    canAccessReports: true,
    canAccessApprovals: true,
    canExecuteDispositions: true,
    canViewAuditLogs: true,
    isReadOnly: false,
  },
  SEKRETARIS: {
    canAccessArchive: true,
    canCreateLetter: true,
    canAccessMinutes: true,
    canAccessJamaah: true,
    canMutateJamaah: false,
    canAccessFinance: false,
    canMutateFinance: false,
    canAccessAssets: true,
    canMutateAssets: false,
    canAccessReports: true,
    canAccessApprovals: false,
    canExecuteDispositions: false,
    canViewAuditLogs: false,
    isReadOnly: false,
  },
  BENDAHARA: {
    canAccessArchive: true,
    canCreateLetter: false,
    canAccessMinutes: false,
    canAccessJamaah: true,
    canMutateJamaah: false,
    canAccessFinance: true,
    canMutateFinance: true,
    canAccessAssets: true,
    canMutateAssets: false,
    canAccessReports: true,
    canAccessApprovals: false,
    canExecuteDispositions: false,
    canViewAuditLogs: false,
    isReadOnly: false,
  },
  SARPRAS: {
    canAccessArchive: false,
    canCreateLetter: false,
    canAccessMinutes: false,
    canAccessJamaah: false,
    canMutateJamaah: false,
    canAccessFinance: false,
    canMutateFinance: false,
    canAccessAssets: true,
    canMutateAssets: true,
    canAccessReports: true,
    canAccessApprovals: false,
    canExecuteDispositions: false,
    canViewAuditLogs: false,
    isReadOnly: false,
  },
  KEMASJIDAN: {
    canAccessArchive: false,
    canCreateLetter: false,
    canAccessMinutes: false,
    canAccessJamaah: true,
    canMutateJamaah: true,
    canAccessFinance: false,
    canMutateFinance: false,
    canAccessAssets: false,
    canMutateAssets: false,
    canAccessReports: true,
    canAccessApprovals: false,
    canExecuteDispositions: false,
    canViewAuditLogs: false,
    isReadOnly: false,
  },
  DEWAN_PENGAWAS: {
    canAccessArchive: true,
    canCreateLetter: false,
    canAccessMinutes: true,
    canAccessJamaah: true,
    canMutateJamaah: false,
    canAccessFinance: true,
    canMutateFinance: false,
    canAccessAssets: true,
    canMutateAssets: false,
    canAccessReports: true,
    canAccessApprovals: true,
    canExecuteDispositions: false,
    canViewAuditLogs: true,
    isReadOnly: true,
  },
};

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'audit-001',
    timestamp: '2026-09-05T05:30:15.000Z',
    userId: 'usr-ketua',
    userName: 'Drs. H. M. Said, M.Pd.',
    userRole: 'KETUA_UMUM',
    userRoleLabel: 'Ketua Umum DKM',
    action: 'LOGIN',
    actionLabel: 'Masuk Sesi Pengurus',
    module: 'AUTENTIKASI',
    description: 'Sesi masuk berhasil dari perangkat pimpinan DKM (IP Makassar 180.252.12.9)',
    ipAddress: '180.252.12.9',
    status: 'SUCCESS',
  },
  {
    id: 'audit-002',
    timestamp: '2026-09-05T05:42:10.000Z',
    userId: 'usr-sekretaris',
    userName: 'M. Yusuf, S.Ag.',
    userRole: 'SEKRETARIS',
    userRoleLabel: 'Sekretaris Umum',
    action: 'CREATE_LETTER',
    actionLabel: 'Penerbitan Surat Resmi',
    module: 'KESEKRETARIATAN',
    description: 'Menerbitkan Surat Undangan Peringatan Maulid Nabi Muhammad SAW 1448 H (No. 004/DKM-MBH/BTP-AE/IX/2026)',
    ipAddress: '180.252.12.14',
    status: 'SUCCESS',
  },
  {
    id: 'audit-003',
    timestamp: '2026-09-05T05:55:00.000Z',
    userId: 'usr-bendahara',
    userName: 'H. Abdul Rahman, S.E.',
    userRole: 'BENDAHARA',
    userRoleLabel: 'Bendahara Umum',
    action: 'CREATE_TRANSACTION',
    actionLabel: 'Pencatatan Kas PHBI',
    module: 'KEUANGAN',
    description: 'Mencatat penerimaan infaq swadaya jamaah khusus PHBI Maulid 1448 H sebesar Rp 4.500.000 pada pos rekening terpisah satu pintu',
    ipAddress: '180.252.12.20',
    status: 'SUCCESS',
  },
  {
    id: 'audit-004',
    timestamp: '2026-09-05T06:05:32.000Z',
    userId: 'usr-sarpras',
    userName: 'Bpk. Irwan Syarifuddin',
    userRole: 'SARPRAS',
    userRoleLabel: 'Koordinator Sarpras',
    action: 'SERVICE_ASSET',
    actionLabel: 'Jadwal Pemeliharaan Aset',
    module: 'SARPRAS',
    description: 'Memperbarui status pemeliharaan berkala AC Standing Floor Daikin 5 PK ruang sholat utama',
    ipAddress: '180.252.12.25',
    status: 'SUCCESS',
  },
  {
    id: 'audit-005',
    timestamp: '2026-09-05T06:12:44.000Z',
    userId: 'usr-kemasjidan',
    userName: 'Ust. H. Syamsuddin, Lc.',
    userRole: 'KEMASJIDAN',
    userRoleLabel: 'Kemasjidan & Dakwah',
    action: 'IMPORT_JAMAAH_EXCEL',
    actionLabel: 'Impor Sensus Excel Massal',
    module: 'JAMAAH',
    description: 'Sinkronisasi data 12 KK warga jamaah RT 03 Blok AE dan pemutakhiran kategori mustahiq zakat',
    ipAddress: '180.252.12.31',
    status: 'SUCCESS',
  },
  {
    id: 'audit-006',
    timestamp: '2026-09-05T06:20:18.000Z',
    userId: 'usr-ketua',
    userName: 'Drs. H. M. Said, M.Pd.',
    userRole: 'KETUA_UMUM',
    userRoleLabel: 'Ketua Umum DKM',
    action: 'APPROVE_DISPOSITION',
    actionLabel: 'Disposisi Pengesahan Satu Pintu',
    module: 'EKSEKUTIF',
    description: 'Mengesahkan pengajuan pencairan operasional honorarium pemateri Tabligh Akbar Maulid melalui Pos PHBI Satu Pintu',
    ipAddress: '180.252.12.9',
    status: 'SUCCESS',
  },
  {
    id: 'audit-007',
    timestamp: '2026-09-05T06:28:05.000Z',
    userId: 'usr-pengawas',
    userName: 'H. M. Arsyad',
    userRole: 'DEWAN_PENGAWAS',
    userRoleLabel: 'Dewan Penasehat / Pengawas',
    action: 'LOGIN',
    actionLabel: 'Mode Pengawas (Read-Only)',
    module: 'AUTENTIKASI',
    description: 'Peninjauan rutin Dewan Pengawas terhadap capaian KPI 4 Pilar dan keseimbangan saldo kas masjid',
    ipAddress: '180.252.12.50',
    status: 'SUCCESS',
  },
];
