import { User, SafeUser, UserRole, RolePermission, AuditLogEntry } from '@/types/auth';

export const OFFICIAL_USERS: User[] = [
  {
    id: 'usr-admin',
    name: 'Administrator TI & Sistem DKM',
    title: 'Super Administrator & Operator IT',
    role: 'SUPER_ADMIN',
    roleLabel: 'Super Admin Sistem',
    email: 'admin@babulkhaer.or.id',
    phone: '0812-4000-0000',
    department: 'Pusat Data & Infrastruktur TI Masjid',
    isReadOnly: false,
    pinHash: '$2b$10$EELfAlg0AdLrq9rdzEIsfuMCCmKN/WtsaC1UC8f5dYkcHI2v0lS16',
    bio: 'Pengelola teknis database cloud Turso, pencadangan dan pemulihan data, otorisasi akun pengguna, dan pengaturan PIN keamanan DKM.',
    status: 'AKTIF',
  },
  {
    id: 'usr-ketua',
    name: 'Drs. Muhammad Hasri, M. Hum.',
    title: 'Ketua Umum DKM',
    role: 'KETUA_UMUM',
    roleLabel: 'Ketua Umum DKM',
    email: 'ketua@babulkhaer.or.id',
    phone: '0812-4000-0001',
    department: 'Badan Pimpinan Harian (Eksekutif)',
    isReadOnly: false,
    pinHash: '$2b$10$EELfAlg0AdLrq9rdzEIsfuMCCmKN/WtsaC1UC8f5dYkcHI2v0lS16',
    bio: 'Pimpinan tertinggi operasional DKM Babul Khaer BTP Blok AE periode 2026-2029 (SK PC DMI Biringkanaya No. 13/2026). Penanggung jawab umum kegiatan kemasjidan, pemegang hak otorisasi pengesahan surat dinas, dan disposisi pencairan kas satu pintu sesuai ART Bagian Ketiga Pasal 3.',
  },
  {
    id: 'usr-sekretaris',
    name: 'Ir. Muhammad Natsir, S.T.',
    title: 'Sekretaris Umum DKM',
    role: 'SEKRETARIS',
    roleLabel: 'Sekretaris Umum',
    email: 'sekretaris@babulkhaer.or.id',
    phone: '0812-4000-0002',
    department: 'Bidang Kesekretariatan & Tata Usaha',
    isReadOnly: false,
    pinHash: '$2b$10$IWF8mlc8SgItEpCLT8eEsOafOu9sAgOhOtJgvpqcZ7PHoL/wy34LO',
    bio: 'Penanggung jawab administrasi umum dan tata usaha kemasjidan DKM Babul Khaer periode 2026-2029 (ART Bagian Kelima Pasal 6). Mengelola persuratan dinas resmi, e-arsip berkas digital, persiapan rapat pleno, notulensi AI, serta memaraf SK kepanitiaan sebelum ditandatangani Ketua Umum.',
  },
  {
    id: 'usr-bendahara',
    name: 'H. Sahali',
    title: 'Bendahara Umum DKM',
    role: 'BENDAHARA',
    roleLabel: 'Bendahara Umum',
    email: 'bendahara@babulkhaer.or.id',
    phone: '0812-4000-0003',
    department: 'Bidang Keuangan & Perbendaharaan',
    isReadOnly: false,
    pinHash: '$2b$10$qPB9.0KGvx2MKyHUC.LF9.M5iMegQVEj8UeiIZ.vW8qkEKdSXcyBC',
    bio: 'Penata dan pengelola administrasi keuangan dan perbendaharaan DKM Babul Khaer periode 2026-2029 (ART Bagian Keenam Pasal 7). Bertanggung jawab atas pembukuan kas harian, laporan berkala mimbar Jumat, pengelolaan pos dana swadaya PHBI satu pintu hasil Raker 2026, dan penerimaan ZISWAF/donatur.',
  },
  {
    id: 'usr-sarpras',
    name: 'Faisal T. Parussengi, S.S.',
    title: 'Koordinator Sarana & Prasarana',
    role: 'SARPRAS',
    roleLabel: 'Koordinator Sarpras',
    email: 'sarpras@babulkhaer.or.id',
    phone: '0812-4000-0004',
    department: 'Bidang Pembangunan, Sarana & Prasarana (Ketua II)',
    isReadOnly: false,
    pinHash: '$2b$10$ILisYBrKnqb86HEIe1nlBOOb71J/NrFCKxHYZSNz0CWnPR8/PCX0S',
    bio: 'Koordinator Seksi Sarana dan Prasarana di bawah naungan Ketua II (H. Muh. Nancha Pattanang, S.E.) periode 2026-2029 (ART Pasal 9). Bertanggung jawab atas inventarisasi kekayaan fisik masjid, pemeliharaan AC Daikin, relokasi modul otomatis genset hasil Raker 2026, sound system, dan fasilitas fisik ibadah.',
  },
  {
    id: 'usr-kemasjidan',
    name: 'Drs. Manai, M.M.',
    title: 'Koordinator Peribadatan & Dakwah',
    role: 'KEMASJIDAN',
    roleLabel: 'Peribadatan & Dakwah',
    email: 'dakwah@babulkhaer.or.id',
    phone: '0812-4000-0005',
    department: 'Bidang Keagamaan, Pendidikan & Organisasi (Ketua I)',
    isReadOnly: false,
    pinHash: '$2b$10$vlgpOVTZlgVX0sqHWgX4NOK7/Xh7uwQmZIdxoGxBCwpmM9AHsva7S',
    bio: 'Koordinator Seksi Peribadatan dan Dakwah di bawah naungan Ketua I (Drs. H. Suardi, M.Pd.) periode 2026-2029 (ART Pasal 8). Mengelola jadwal sholat fardhu/Jumat, penetapan insentif imam rawatib Rp1.500.000 hasil Raker 2026, sensus jamaah RT 01-05 Blok AE, dan pemetaan mustahiq zakat.',
  },
  {
    id: 'usr-pengawas',
    name: 'Dr. Andi Fiptar Abdi Alam, M. Si.',
    title: 'Koordinator Dewan Pengawas & Pemeriksa',
    role: 'DEWAN_PENGAWAS',
    roleLabel: 'Dewan Pengawas & Pemeriksa',
    email: 'pengawas@babulkhaer.or.id',
    phone: '0812-4000-0006',
    department: 'Badan Pengawas & Pemeriksa Keuangan DKM',
    isReadOnly: true,
    pinHash: '$2b$10$9oUuPw9MYw6YEWYpfnRo5uTEI2puiSLEUVPrrkrO7kCMidpFyQpOi',
    bio: 'Koordinator Dewan Pengawas dan Pemeriksa DKM Babul Khaer periode 2026-2029 (SK PC DMI No. 13/2026 & ART Bagian Kedua Pasal 2 ayat 3). Menjalankan amanah independen pengawasan dan pemeriksaan penggunaan dana kas masjid, evaluasi pencapaian kinerja 4 pilar DKM, dan audit kepatuhan AD/ART (Mode Akses Read-Only).',
  },
];

/**
 * Mengembalikan data pengurus yang aman dikirim ke publik (tanpa pinHash, phone, email)
 */
export function getSafeOfficials(): SafeUser[] {
  return OFFICIAL_USERS.map((u) => ({
    id: u.id,
    name: u.name,
    title: u.title,
    role: u.role,
    roleLabel: u.roleLabel,
    avatarUrl: u.avatarUrl,
    department: u.department,
    isReadOnly: u.isReadOnly,
    bio: u.bio,
  }));
}

export const ROLE_PERMISSIONS: Record<UserRole, RolePermission> = {
  SUPER_ADMIN: {
    canAccessArchive: true,
    canCreateLetter: true,
    canAccessMinutes: true,
    canAccessJamaah: true,
    canMutateJamaah: true,
    canAccessFinance: true,
    canMutateFinance: true,
    canAccessAssets: true,
    canMutateAssets: true,
    canAccessReports: true,
    canAccessApprovals: true,
    canExecuteDispositions: true,
    canViewAuditLogs: true,
    canAccessSuperAdmin: true,
    isReadOnly: false,
  },
  KETUA_UMUM: {
    canAccessArchive: true,
    canCreateLetter: true,
    canAccessMinutes: true,
    canAccessJamaah: true,
    canMutateJamaah: true,
    canAccessFinance: true,
    canMutateFinance: true,
    canAccessAssets: true,
    canMutateAssets: true,
    canAccessReports: true,
    canAccessApprovals: true,
    canExecuteDispositions: true,
    canViewAuditLogs: true,
    canAccessSuperAdmin: true,
    isReadOnly: false,
  },
  SEKRETARIS: {
    canAccessArchive: true,
    canCreateLetter: true,
    canAccessMinutes: true,
    canAccessJamaah: false,
    canMutateJamaah: false,
    canAccessFinance: false,
    canMutateFinance: false,
    canAccessAssets: false,
    canMutateAssets: false,
    canAccessReports: true,
    canAccessApprovals: false,
    canExecuteDispositions: false,
    canViewAuditLogs: false,
    canAccessSuperAdmin: false,
    isReadOnly: false,
  },
  BENDAHARA: {
    canAccessArchive: false,
    canCreateLetter: false,
    canAccessMinutes: false,
    canAccessJamaah: false,
    canMutateJamaah: false,
    canAccessFinance: true,
    canMutateFinance: true,
    canAccessAssets: false,
    canMutateAssets: false,
    canAccessReports: true,
    canAccessApprovals: false,
    canExecuteDispositions: false,
    canViewAuditLogs: false,
    canAccessSuperAdmin: false,
    isReadOnly: false,
  },
  SARPRAS: {
    canAccessArchive: false,
    canCreateLetter: false,
    canAccessMinutes: false,
    canAccessJamaah: false,
    canMutateJamaah: false,
    canAccessFinance: false,
    canMutateFinance: false,
    canAccessAssets: true,
    canMutateAssets: true,
    canAccessReports: true,
    canAccessApprovals: false,
    canExecuteDispositions: false,
    canViewAuditLogs: false,
    canAccessSuperAdmin: false,
    isReadOnly: false,
  },
  KEMASJIDAN: {
    canAccessArchive: false,
    canCreateLetter: false,
    canAccessMinutes: false,
    canAccessJamaah: true,
    canMutateJamaah: true,
    canAccessFinance: false,
    canMutateFinance: false,
    canAccessAssets: false,
    canMutateAssets: false,
    canAccessReports: true,
    canAccessApprovals: false,
    canExecuteDispositions: false,
    canViewAuditLogs: false,
    canAccessSuperAdmin: false,
    isReadOnly: false,
  },
  DEWAN_PENGAWAS: {
    canAccessArchive: false,
    canCreateLetter: false,
    canAccessMinutes: false,
    canAccessJamaah: false,
    canMutateJamaah: false,
    canAccessFinance: false,
    canMutateFinance: false,
    canAccessAssets: false,
    canMutateAssets: false,
    canAccessReports: true,
    canAccessApprovals: false,
    canExecuteDispositions: false,
    canViewAuditLogs: true,
    canAccessSuperAdmin: false,
    isReadOnly: true,
  },
};

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'audit-001',
    timestamp: '2026-09-05T05:30:15.000Z',
    userId: 'usr-ketua',
    userName: 'Drs. Muhammad Hasri, M. Hum.',
    userRole: 'KETUA_UMUM',
    userRoleLabel: 'Ketua Umum DKM',
    action: 'LOGIN',
    actionLabel: 'Masuk Sesi Pengurus',
    module: 'AUTENTIKASI',
    description: 'Sesi masuk berhasil dari perangkat pimpinan DKM (IP Makassar 180.252.12.9)',
    ipAddress: '180.252.12.9',
    status: 'SUCCESS',
  },
  {
    id: 'audit-002',
    timestamp: '2026-09-05T05:42:10.000Z',
    userId: 'usr-sekretaris',
    userName: 'Ir. Muhammad Natsir, S.T.',
    userRole: 'SEKRETARIS',
    userRoleLabel: 'Sekretaris Umum',
    action: 'CREATE_LETTER',
    actionLabel: 'Penerbitan Surat Resmi',
    module: 'KESEKRETARIATAN',
    description: 'Menerbitkan Surat Undangan Peringatan Maulid Nabi Muhammad SAW 1448 H (No. 004/DKM-MBH/BTP-AE/IX/2026)',
    ipAddress: '180.252.12.14',
    status: 'SUCCESS',
  },
  {
    id: 'audit-003',
    timestamp: '2026-09-05T05:55:00.000Z',
    userId: 'usr-bendahara',
    userName: 'H. Sahali',
    userRole: 'BENDAHARA',
    userRoleLabel: 'Bendahara Umum',
    action: 'CREATE_TRANSACTION',
    actionLabel: 'Pencatatan Kas PHBI',
    module: 'KEUANGAN',
    description: 'Mencatat penerimaan infaq swadaya jamaah khusus PHBI Maulid 1448 H sebesar Rp 4.500.000 pada pos rekening terpisah satu pintu',
    ipAddress: '180.252.12.20',
    status: 'SUCCESS',
  },
  {
    id: 'audit-004',
    timestamp: '2026-09-05T06:05:32.000Z',
    userId: 'usr-sarpras',
    userName: 'Faisal T. Parussengi, S.S.',
    userRole: 'SARPRAS',
    userRoleLabel: 'Koordinator Sarpras',
    action: 'SERVICE_ASSET',
    actionLabel: 'Jadwal Pemeliharaan Aset',
    module: 'SARPRAS',
    description: 'Memperbarui status pemeliharaan berkala AC Standing Floor Daikin 5 PK ruang sholat utama',
    ipAddress: '180.252.12.25',
    status: 'SUCCESS',
  },
  {
    id: 'audit-005',
    timestamp: '2026-09-05T06:12:44.000Z',
    userId: 'usr-kemasjidan',
    userName: 'Drs. Manai, M.M.',
    userRole: 'KEMASJIDAN',
    userRoleLabel: 'Peribadatan & Dakwah',
    action: 'IMPORT_JAMAAH_EXCEL',
    actionLabel: 'Impor Sensus Excel Massal',
    module: 'JAMAAH',
    description: 'Sinkronisasi data 12 KK warga jamaah RT 03 Blok AE dan pemutakhiran kategori mustahiq zakat',
    ipAddress: '180.252.12.31',
    status: 'SUCCESS',
  },
  {
    id: 'audit-006',
    timestamp: '2026-09-05T06:20:18.000Z',
    userId: 'usr-ketua',
    userName: 'Drs. Muhammad Hasri, M. Hum.',
    userRole: 'KETUA_UMUM',
    userRoleLabel: 'Ketua Umum DKM',
    action: 'APPROVE_DISPOSITION',
    actionLabel: 'Disposisi Pengesahan Satu Pintu',
    module: 'EKSEKUTIF',
    description: 'Mengesahkan pengajuan pencairan operasional honorarium pemateri Tabligh Akbar Maulid melalui Pos PHBI Satu Pintu',
    ipAddress: '180.252.12.9',
    status: 'SUCCESS',
  },
  {
    id: 'audit-007',
    timestamp: '2026-09-05T06:28:05.000Z',
    userId: 'usr-pengawas',
    userName: 'Dr. Andi Fiptar Abdi Alam, M. Si.',
    userRole: 'DEWAN_PENGAWAS',
    userRoleLabel: 'Dewan Pengawas & Pemeriksa',
    action: 'LOGIN',
    actionLabel: 'Mode Pengawas (Read-Only)',
    module: 'AUTENTIKASI',
    description: 'Peninjauan rutin Dewan Pengawas terhadap capaian KPI 4 Pilar dan keseimbangan saldo kas masjid',
    ipAddress: '180.252.12.50',
    status: 'SUCCESS',
  },
];
