import { Santri, TpaTeacher } from '@/types/tpa';

export const INITIAL_TPA_TEACHERS: TpaTeacher[] = [
  {
    id: 'tch-001',
    name: 'Ustadzah Nur Aisyah, S.Pd.I',
    phone: '0812-3344-5501',
    specialization: 'Tahfidz Juz 30 & Tajwid Al-Qur\'an',
    schedule: 'Senin - Kamis (16.00 - 17.30 WITA)',
    studentCount: 18,
    allowanceMonthly: 1200000,
    status: 'AKTIF',
  },
  {
    id: 'tch-002',
    name: 'Ustadzah Rahmawati, S.Hum.',
    phone: '0852-6677-8802',
    specialization: 'Iqro 3 - 6 & Fikih Ibadah Dasar',
    schedule: 'Senin - Kamis (16.00 - 17.30 WITA)',
    studentCount: 22,
    allowanceMonthly: 1000000,
    status: 'AKTIF',
  },
  {
    id: 'tch-003',
    name: 'Ustadzah Fatimah Azzahra',
    phone: '0821-9988-7703',
    specialization: 'Iqro 1 - 2 & Hafalan Doa Harian',
    schedule: 'Senin - Kamis (16.00 - 17.30 WITA)',
    studentCount: 20,
    allowanceMonthly: 1000000,
    status: 'AKTIF',
  },
  {
    id: 'tch-004',
    name: 'Ust. Muh. Ridwan, S.Ag.',
    phone: '0813-1122-3304',
    specialization: 'Tahsin & Nagham Tilawah Remaja',
    schedule: 'Jumat & Sabtu (16.00 - 17.30 WITA)',
    studentCount: 12,
    allowanceMonthly: 800000,
    status: 'AKTIF',
  },
];

export const INITIAL_SANTRI_LIST: Santri[] = [
  {
    id: 'san-001',
    nis: 'BK-TPA-2025-001',
    name: 'Muhammad Faiz Pratama',
    gender: 'L',
    age: 9,
    level: 'Tahfidz Juz 30',
    parentName: 'H. Rusli Hasan',
    parentPhone: '0813-5566-7788',
    address: 'BTP Blok AE No. 15',
    sppStatus: 'LUNAS',
    monthlyFee: 75000,
    joinDate: '2025-01-10',
    teacherId: 'tch-001',
    teacherName: 'Ustadzah Nur Aisyah, S.Pd.I',
    hafalanCount: 'Juz 30 (Lulus 22 Surat)',
    lastAssessment: 'Tajwid sangat baik, makharijul huruf fasih',
  },
  {
    id: 'san-002',
    nis: 'BK-TPA-2025-002',
    name: 'Aisyah Humaira Putri',
    gender: 'P',
    age: 7,
    level: 'Iqro 3-4',
    parentName: 'Bambang Sudarmono',
    parentPhone: '0812-4455-6677',
    address: 'BTP Blok AE No. 28',
    sppStatus: 'LUNAS',
    monthlyFee: 75000,
    joinDate: '2025-02-15',
    teacherId: 'tch-002',
    teacherName: 'Ustadzah Rahmawati, S.Hum.',
    hafalanCount: 'Surah Al-Fatihah s.d Al-Maun',
    lastAssessment: 'Iqro jilid 3 halaman 18, bacaan lancar',
  },
  {
    id: 'san-003',
    nis: 'BK-TPA-2025-003',
    name: 'Fathir Ahmad Dani',
    gender: 'L',
    age: 6,
    level: 'Iqro 1-2',
    parentName: 'Pak Amiruddin (Satpam RW)',
    parentPhone: '0852-1133-5577',
    address: 'Pos Keamanan Blok AE',
    sppStatus: 'BEASISWA_DKM',
    monthlyFee: 0,
    joinDate: '2025-03-01',
    teacherId: 'tch-003',
    teacherName: 'Ustadzah Fatimah Azzahra',
    hafalanCount: 'Surah Al-Ikhlas, Al-Falaq, An-Nas',
    lastAssessment: 'Mulai mengenal huruf hijaiyah berharakat fathah',
  },
  {
    id: 'san-004',
    nis: 'BK-TPA-2025-004',
    name: 'Nabila Zahra Khairunnisa',
    gender: 'P',
    age: 11,
    level: 'Tahfidz Juz 30',
    parentName: 'Ir. Ruslan Effendi',
    parentPhone: '0811-9988-7766',
    address: 'BTP Blok AE No. 04',
    sppStatus: 'LUNAS',
    monthlyFee: 75000,
    joinDate: '2024-08-01',
    teacherId: 'tch-001',
    teacherName: 'Ustadzah Nur Aisyah, S.Pd.I',
    hafalanCount: 'Juz 30 (Khatam)',
    lastAssessment: 'Siap ujian sertifikasi munaqasyah BKPRMI',
  },
  {
    id: 'san-005',
    nis: 'BK-TPA-2025-005',
    name: 'Rafi Al-Ghifari',
    gender: 'L',
    age: 8,
    level: 'Iqro 5-6',
    parentName: 'H. Sahali',
    parentPhone: '0812-7788-9900',
    address: 'BTP Blok AE No. 33',
    sppStatus: 'LUNAS',
    monthlyFee: 75000,
    joinDate: '2025-01-12',
    teacherId: 'tch-002',
    teacherName: 'Ustadzah Rahmawati, S.Hum.',
    hafalanCount: 'Surah At-Takatsur s.d An-Nas',
    lastAssessment: 'Sedang latihan waqaf dan ibtida di Iqro 6',
  },
  {
    id: 'san-006',
    nis: 'BK-TPA-2025-006',
    name: 'Khadijah Annur',
    gender: 'P',
    age: 5,
    level: 'Iqro 1-2',
    parentName: 'Wahyu Hidayat',
    parentPhone: '0822-4466-8800',
    address: 'BTP Blok AE No. 51',
    sppStatus: 'MENUNGGAK',
    monthlyFee: 75000,
    joinDate: '2025-05-10',
    teacherId: 'tch-003',
    teacherName: 'Ustadzah Fatimah Azzahra',
    hafalanCount: 'Doa sebelum makan & tidur',
    lastAssessment: 'Perlu bimbingan sabar pengucapan huruf tsa & dza',
  },
  {
    id: 'san-007',
    nis: 'BK-TPA-2025-007',
    name: 'Bilal Habibi',
    gender: 'L',
    age: 12,
    level: 'Tahfidz Lanjutan',
    parentName: 'Drs. H. Suardi',
    parentPhone: '0811-4411-2233',
    address: 'BTP Blok AE No. 12',
    sppStatus: 'LUNAS',
    monthlyFee: 75000,
    joinDate: '2024-01-05',
    teacherId: 'tch-004',
    teacherName: 'Ust. Muh. Ridwan, S.Ag.',
    hafalanCount: 'Juz 29 (Al-Mulk, Al-Qalam, Al-Haqqah)',
    lastAssessment: 'Irama murottal merdu dan tartil',
  },
  {
    id: 'san-008',
    nis: 'BK-TPA-2025-008',
    name: 'Siti Maryam',
    gender: 'P',
    age: 10,
    level: 'Al-Quran Dasar',
    parentName: 'Ibu Nurhayati',
    parentPhone: '0853-2244-6688',
    address: 'BTP Blok AE No. 60',
    sppStatus: 'BEASISWA_DKM',
    monthlyFee: 0,
    joinDate: '2024-11-15',
    teacherId: 'tch-001',
    teacherName: 'Ustadzah Nur Aisyah, S.Pd.I',
    hafalanCount: 'Juz 30 (Surah Ad-Dhuha s.d An-Nas)',
    lastAssessment: 'Mulai tadarrus Surah Al-Baqarah ayat 1-50',
  },
];
