import {
  FridayScheduleItem,
  RawatibScheduleItem,
  KajianScheduleItem,
  RamadhanScheduleItem,
  KhatibItem,
} from '@/types/dakwah';

export const INITIAL_KHATIB_DATABASE: KhatibItem[] = [
  {
    id: 'ktb-001',
    name: 'Dr. Drs. H. Andi Hasanuddin, M.M.',
    title: 'Dewan Penasihat DKM / Ulama Makassar',
    specialization: 'Fiqih Muamalah & Ukhuwah Islamiyah',
    institution: 'PC DMI Biringkanaya / MUI Kota Makassar',
    phone: '0812-4111-2200',
    address: 'Kompleks BTP Blok AE No. 15 Tamalanrea',
    totalAppearances: 14,
    status: 'AKTIF',
    notes: 'Khatib senior, materi sangat mendalam dan diminati jamaah shalat Jumat.',
    createdAt: '2026-01-10T08:00:00.000Z',
  },
  {
    id: 'ktb-002',
    name: 'Drs. H. Muh. Rusdi Lahajji, M. Pd.',
    title: 'Dosen / Pengurus PC DMI Biringkanaya',
    specialization: 'Fiqih Ibadah & Sosial Kemasyarakatan',
    institution: 'PC DMI Biringkanaya / Universitas Islam',
    phone: '0812-4111-2201',
    address: 'Katimbang, Biringkanaya, Kota Makassar',
    totalAppearances: 18,
    status: 'AKTIF',
    notes: 'Koordinator Seksi Humas & Sosial SK 2026, aktif mengisi kajian subuh.',
    createdAt: '2026-01-15T08:00:00.000Z',
  },
  {
    id: 'ktb-003',
    name: 'Drs. Ahmad Sumadiana',
    title: 'Tokoh Agama Katimbang / Imam Rawatib 2',
    specialization: 'Aqidah Praktis & Fiqih Shalat Berjamaah',
    institution: 'DKM Masjid Babul Khaer',
    phone: '0812-4111-2202',
    address: 'Kompleks BTP Blok AE No. 32',
    totalAppearances: 12,
    status: 'AKTIF',
    notes: 'Imam Rawatib sholat fardhu siang hari, fasih dalam kajian kitab kuning.',
    createdAt: '2026-02-01T08:00:00.000Z',
  },
  {
    id: 'ktb-004',
    name: 'Ust. Habibi, S.H.',
    title: 'Dai Muda Biringkanaya',
    specialization: 'Pembinaan Remaja, Akhlak & Pemuda Hijrah',
    institution: 'Ikatan Remaja Masjid (BKPRMI Biringkanaya)',
    phone: '0812-4111-2203',
    address: 'Pacerakkang, Biringkanaya',
    totalAppearances: 9,
    status: 'AKTIF',
    notes: 'Penyampaian komunikatif dan sangat disukai generasi muda masjid.',
    createdAt: '2026-02-10T08:00:00.000Z',
  },
  {
    id: 'ktb-005',
    name: 'Ust. Agustam Ibrahim Yusuf, S.Pd.I.',
    title: 'Penyuluh Agama KUA Biringkanaya',
    specialization: 'ZISWAF, Fiqih Mawaris & Konsultasi Syariah',
    institution: 'KUA Kecamatan Biringkanaya',
    phone: '0812-4111-2204',
    address: 'Bumi Permata Sudiang Makassar',
    totalAppearances: 11,
    status: 'AKTIF',
    notes: 'Rutin memberikan bimbingan kemitraan Kemenag dengan DKM Babul Khaer.',
    createdAt: '2026-02-20T08:00:00.000Z',
  },
  {
    id: 'ktb-006',
    name: 'Fathan Mubin Hasri, S. Pd.I.',
    title: 'Instruktur Tahsinul Quran / Imam Rawatib 3',
    specialization: 'Tahsin, Makhorijul Huruf & Qiraat Al-Qur\'an',
    institution: 'Lembaga Pendidikan Al-Qur\'an Babul Khaer',
    phone: '0812-4111-2205',
    address: 'Kompleks BTP Blok AE No. 08',
    totalAppearances: 8,
    status: 'AKTIF',
    notes: 'Qari berprestasi, membina kelas tahsin dewasa dan remaja setiap pekan.',
    createdAt: '2026-03-01T08:00:00.000Z',
  },
  {
    id: 'ktb-007',
    name: 'Prof. Dr. Ir. Lamatinulu, M.T., IPU',
    title: 'Dewan Pengawas DKM / Guru Besar Teknik',
    specialization: 'Integrasi Sains, Etika Profesional & Nilai Islam',
    institution: 'Dewan Pengawas DKM / Perguruan Tinggi Negeri',
    phone: '0812-4111-2206',
    address: 'Kompleks BTP Blok AE No. 50',
    totalAppearances: 6,
    status: 'CADANGAN',
    notes: 'Khatib spesialis momentum Isra Mi\'raj dan Peringatan Hari Besar Islam.',
    createdAt: '2026-03-15T08:00:00.000Z',
  },
  {
    id: 'ktb-008',
    name: 'Dr. Andi Fiptar Abdi Alam, M. Si.',
    title: 'Koordinator Dewan Pengawas / Akademisi',
    specialization: 'Kepemimpinan Islam & Manajemen Kemakmuran Masjid',
    institution: 'Badan Pengawas DKM Babul Khaer',
    phone: '0812-4111-2207',
    address: 'Kompleks BTP Blok AE No. 22',
    totalAppearances: 7,
    status: 'CADANGAN',
    notes: 'Pemateri kajian tematik Ramadhan dan pengawasan tata kelola DKM.',
    createdAt: '2026-04-01T08:00:00.000Z',
  },
];

export const INITIAL_FRIDAY_SCHEDULES: FridayScheduleItem[] = [
  {
    id: 'fri-000',
    date: '2026-09-04',
    dateHijri: '22 Safar 1448 H',
    khatibName: 'Dr. Drs. H. Andi Hasanuddin, M.M.',
    khatibTitle: 'Dewan Penasihat DKM / Ulama Makassar',
    imamName: 'Drs. Manai, M.M.',
    khutbahTopic: 'Rasa Syukur dan Semangat Kebersamaan Mengawali Amanah Kepengurusan Baru',
    phone: '0812-4111-2200',
    status: 'SELESAI',
    incentiveAmount: 1500000,
    isCompleted: true,
    attendanceCount: 290,
    actualHonorDisbursed: 1500000,
    summaryNotes: 'Khutbah Jumat perdana pasca Raker 2026 berjalan khidmat. Seluruh saf lantai 1 penuh dan tertib.',
    completedAt: '2026-09-04T13:15:00.000Z',
    notes: 'Khutbah selesai tepat waktu pukul 12.45 WITA, disiarkan melalui sound system baru.',
  },
  {
    id: 'fri-001',
    date: '2026-09-11',
    dateHijri: '29 Safar 1448 H',
    khatibName: 'Drs. H. Muh. Rusdi Lahajji, M. Pd.',
    khatibTitle: 'Dosen / Pengurus PC DMI Biringkanaya',
    imamName: 'Drs. Manai, M.M.',
    khutbahTopic: 'Menjaga Kesucian Niat dan Mengokohkan Kemakmuran Masjid',
    phone: '0812-4111-2201',
    status: 'TERKONFIRMASI',
    incentiveAmount: 1500000,
    isCompleted: false,
    notes: 'Khutbah durasi maksimal 20 menit, mikrofon nirkabel telah disiapkan operator.',
  },
  {
    id: 'fri-002',
    date: '2026-09-18',
    dateHijri: '7 Rabiul Awal 1448 H',
    khatibName: 'Drs. Ahmad Sumadiana',
    khatibTitle: 'Tokoh Agama Katimbang',
    imamName: 'Drs. Manai, M.M.',
    khutbahTopic: 'Ukhuwah Islamiyah sebagai Pondasi Kekuatan Umat di Lingkungan Warga',
    phone: '0812-4111-2202',
    status: 'TERKONFIRMASI',
    incentiveAmount: 1500000,
    isCompleted: false,
    notes: 'Konfirmasi via WhatsApp terverifikasi tanggal 5 September 2026.',
  },
  {
    id: 'fri-003',
    date: '2026-09-25',
    dateHijri: '14 Rabiul Awal 1448 H',
    khatibName: 'Ust. Habibi, S.H.',
    khatibTitle: 'Dai Muda Biringkanaya',
    imamName: 'Fathan Mubin Hasri, S. Pd.I.',
    khutbahTopic: 'Keteladanan Akhlak Rasulullah SAW dalam Membangun Generasi Qurani',
    phone: '0812-4111-2203',
    status: 'MENUNGGU',
    incentiveAmount: 1500000,
    isCompleted: false,
    notes: 'Menunggu konfirmasi kehadiran H-3 dari Seksi Peribadatan.',
  },
  {
    id: 'fri-004',
    date: '2026-10-02',
    dateHijri: '21 Rabiul Awal 1448 H',
    khatibName: 'Ust. Agustam Ibrahim Yusuf, S.Pd.I.',
    khatibTitle: 'Penyuluh Agama KUA Biringkanaya',
    imamName: 'Drs. Manai, M.M.',
    khutbahTopic: 'Urgensi Zakat, Infaq, dan Sedekah bagi Pengentasan Kemiskinan Jamaah',
    phone: '0812-4111-2204',
    status: 'MENUNGGU',
    incentiveAmount: 1500000,
    isCompleted: false,
    notes: 'Jadwal rutin triwulanan KUA.',
  },
];

export const INITIAL_RAWATIB_SCHEDULES: RawatibScheduleItem[] = [
  {
    id: 'rwt-001',
    name: 'Drs. Manai, M.M.',
    role: 'IMAM_RAWATIB',
    roleLabel: 'Imam Rawatib 1 (Koordinator)',
    assignedPrayers: ['Subuh', 'Maghrib', 'Isya'],
    monthlyIncentive: 1500000,
    phone: '0813-5501-9001',
    status: 'AKTIF',
    notes: 'Mengikuti standar insentif baru hasil keputusan pleno Raker 2026 (usulan Pak Hasri).',
  },
  {
    id: 'rwt-002',
    name: 'Drs. Ahmad Sumadiana',
    role: 'IMAM_RAWATIB',
    roleLabel: 'Imam Rawatib 2',
    assignedPrayers: ['Dzuhur', 'Ashar'],
    monthlyIncentive: 1500000,
    phone: '0813-5501-9002',
    status: 'AKTIF',
    notes: 'Bertugas rutin sholat siang hari dan menjadi imam pengganti jika Imam 1 berhalangan.',
  },
  {
    id: 'rwt-003',
    name: 'Fathan Mubin Hasri, S. Pd.I.',
    role: 'IMAM_RAWATIB',
    roleLabel: 'Imam Rawatib 3 (Muda)',
    assignedPrayers: ['Isya (Jumat/Sabtu)', 'Cadangan Subuh'],
    monthlyIncentive: 1500000,
    phone: '0813-5501-9003',
    status: 'AKTIF',
    notes: 'Fokus pembinaan bacaan tartil bagi generasi remaja masjid.',
  },
  {
    id: 'rwt-004',
    name: 'Firman (Marbot Azan)',
    role: 'MARBOT_AZAN',
    roleLabel: 'Petugas Marbot & Muadzin Tepat Waktu',
    assignedPrayers: ['Subuh', 'Dzuhur', 'Ashar', 'Maghrib', 'Isya'],
    monthlyIncentive: 1000000,
    phone: '0813-5501-9004',
    status: 'AKTIF',
    notes: 'Sesuai usulan Pak Suardi di Raker: Memastikan waktu adzan berkumandang tepat jadwal waktu sholat.',
  },
];

export const INITIAL_KAJIAN_SCHEDULES: KajianScheduleItem[] = [
  {
    id: 'kjn-000',
    title: 'Kajian Rutin Subuh Ahad Lalu',
    type: 'PEKANAN',
    speakerName: 'Drs. Manai, M.M.',
    speakerTitle: 'Koordinator Seksi Peribadatan & Dakwah',
    bookOrTopic: 'Adab Beribadah dan Kebersihan Fasilitas Masjid',
    dayTime: 'Ahad, 31 Agustus 2026 — 05.30 WITA',
    location: 'Ruang Sholat Utama Masjid Babul Khaer',
    fundingSource: 'SWADAYA_JAMAAH',
    contactPerson: 'Syafruddin (0812-4200-1122)',
    isCompleted: true,
    attendanceCount: 65,
    actualHonorDisbursed: 200000,
    summaryNotes: 'Kajian subuh dihadiri 65 jamaah. Pembahasan fokus pada adab menjaga kesucian lantai masjid dan hemat air wudhu.',
    completedAt: '2026-08-31T06:45:00.000Z',
    notes: 'Terselenggara sukses dengan sarapan pagi swadaya majelis taklim.',
  },
  {
    id: 'kjn-001',
    title: 'Kajian Rutin Subuh Ahad Mendatang',
    type: 'PEKANAN',
    speakerName: 'Drs. Manai, M.M.',
    speakerTitle: 'Koordinator Seksi Peribadatan & Dakwah',
    bookOrTopic: 'Tafsir Surat Pendek & Fiqih Ibadah Praktis',
    dayTime: "Setiap Ahad Ba'da Sholat Subuh (05.30 - 06.30 WITA)",
    location: 'Ruang Sholat Utama Masjid Babul Khaer',
    fundingSource: 'SWADAYA_JAMAAH',
    contactPerson: 'Syafruddin (0812-4200-1122)',
    isCompleted: false,
    notes: 'Maksimal 2x dalam sepekan, dana dicarikan sendiri swadaya jamaah (TIDAK memakai kas masjid).',
  },
  {
    id: 'kjn-002',
    title: 'Kajian Tematik Malam Jumat',
    type: 'PEKANAN',
    speakerName: 'Ust. Agustam Ibrahim Yusuf, S.Pd.I.',
    speakerTitle: 'Dai Komisi Dakwah',
    bookOrTopic: 'Tazkiyatun Nafs & Adab Islami dalam Rumah Tangga',
    dayTime: "Setiap Kamis Ba'da Maghrib s/d Isya",
    location: 'Ruang Sholat Utama Masjid Babul Khaer',
    fundingSource: 'SWADAYA_JAMAAH',
    contactPerson: 'Fakhri Pradana (0812-4200-1123)',
    isCompleted: false,
    notes: 'Pengumuman dicetak dan ditempel di papan bicara serambi masjid.',
  },
  {
    id: 'kjn-003',
    title: 'Tabligh Akbar Peringatan Maulid Nabi 1448 H',
    type: 'TABLIGH_AKBAR',
    speakerName: 'Dr. Drs. H. Andi Hasanuddin, M.M.',
    speakerTitle: 'Dewan Penasihat DKM / Ulama Makassar',
    bookOrTopic: 'Merajut Ukhuwah Meneladani Rasulullah SAW di Era Modern',
    dayTime: 'Ahad, 20 September 2026 — 19.30 WITA',
    location: 'Pelataran & Ruang Sholat Utama Masjid',
    fundingSource: 'SWADAYA_JAMAAH',
    contactPerson: 'Ir. Muhammad Natsir, S.T. (0812-4000-0002)',
    isCompleted: false,
    notes: 'Dana swadaya satu pintu Bendahara Umum (H. Sahali), tidak melibatkan kas operasional masjid.',
  },
  {
    id: 'kjn-004',
    title: 'Program Bimbingan Tahsin Al-Qur\'an Dewasa & Remaja',
    type: 'TAHSIN',
    speakerName: 'Ust. Muhammad Anas & Fathan Mubin, S.Pd.I.',
    speakerTitle: 'Instruktur Tahsinul Quran',
    bookOrTopic: 'Metode As-Syafi\'i: Makhorijul Huruf dan Sifat Huruf',
    dayTime: "Selasa & Jumat Ba'da Ashar (16.00 - 17.30 WITA)",
    location: 'Serambi Kanan Masjid Babul Khaer',
    fundingSource: 'SWADAYA_JAMAAH',
    contactPerson: 'Muhammad Arfah (0812-4200-1125)',
    isCompleted: false,
    notes: 'Terbuka gratis untuk seluruh jamaah Blok AE.',
  },
];

export const INITIAL_RAMADHAN_SCHEDULES: RamadhanScheduleItem[] = [
  {
    id: 'rmd-001',
    nightNumber: 1,
    date: '1 Ramadhan 1448 H',
    penceramahTarawih: 'Drs. Muhammad Hasri, M. Hum.',
    topicKultum: 'Marhaban Ya Ramadhan: Momentum Pembersihan Jiwa dan Harta',
    honorPenceramah: 400000,
    imamTarawih: 'Drs. Manai, M.M.',
    honorImamTarawih: 300000,
    bukberHost: 'Pengurus DKM & Tokoh Masyarakat BTP Blok AE',
    bukberPax: 150,
    itikafStatus: 'TIDAK_ADA',
    isCompleted: false,
  },
  {
    id: 'rmd-002',
    nightNumber: 2,
    date: '2 Ramadhan 1448 H',
    penceramahTarawih: 'Drs. H. Suardi, M. Pd.',
    topicKultum: 'Puasa Menumbuhkan Empati dan Kepedulian Sosial kepada Kaum Dhuafa',
    honorPenceramah: 400000,
    imamTarawih: 'Drs. Ahmad Sumadiana',
    honorImamTarawih: 300000,
    bukberHost: 'Jamaah Warga RT 01 BTP Blok AE',
    bukberPax: 120,
    itikafStatus: 'TIDAK_ADA',
    isCompleted: false,
  },
  {
    id: 'rmd-003',
    nightNumber: 3,
    date: '3 Ramadhan 1448 H',
    penceramahTarawih: 'Ust. Habibi, S.H.',
    topicKultum: 'Keutamaan Al-Qur\'an dan Menjaga Keistiqamahan Tadarrus',
    honorPenceramah: 400000,
    imamTarawih: 'Fathan Mubin Hasri, S. Pd.I.',
    honorImamTarawih: 300000,
    bukberHost: 'Jamaah Warga RT 02 BTP Blok AE',
    bukberPax: 120,
    itikafStatus: 'TIDAK_ADA',
    isCompleted: false,
  },
  {
    id: 'rmd-021',
    nightNumber: 21,
    date: '21 Ramadhan 1448 H',
    penceramahTarawih: 'Dr. Andi Fiptar Abdi Alam, M. Si.',
    topicKultum: 'Menjemput Lailatul Qadar dengan Qiyamul Lail dan I\'tikaf Khusyuk',
    honorPenceramah: 400000,
    imamTarawih: 'Drs. Manai, M.M.',
    honorImamTarawih: 300000,
    bukberHost: 'Majelis Taklim Muslimah & Donatur Swadaya',
    bukberPax: 200,
    itikafStatus: 'TERJADWAL',
    isCompleted: false,
  },
];
