import { UmkmBusiness } from '@/types/umkm';

export const INITIAL_UMKM_LIST: UmkmBusiness[] = [
  {
    id: 'umkm-001',
    name: 'Dapur Berkah Bu Rosdiana (Kue Tradisional & Nasi Kotak)',
    category: 'KULINER_HALAL',
    ownerName: 'Hj. Rosdiana',
    phone: '0852-9988-3344',
    rt: 'RT 01',
    address: 'BTP Blok AE No. 05',
    description: 'Menyediakan aneka kue basah khas Bugis-Makassar (Barongko, Taripang, Jalangkote) dan katering nasi kotak pengajian.',
    products: ['Jalangkote Renyah', 'Barongko Gula Merah', 'Nasi Kotak Ayam Bakar Berkah'],
    priceRange: 'Rp 2.500 - Rp 35.000',
    bazarParticipant: true,
    qardhFacility: {
      hasLoan: true,
      loanAmount: 5000000,
      disbursedDate: '2026-03-01',
      remainingAmount: 1250000,
      monthlyInstallment: 416666,
      status: 'LANCAR',
    },
    verifiedByDkm: true,
  },
  {
    id: 'umkm-002',
    name: 'Gerai Hijab & Busana Muslimah Aisyah',
    category: 'BUSANA_MUSLIM',
    ownerName: 'Ibu Nurhayati (Wali Santri)',
    phone: '0853-2244-6688',
    rt: 'RT 02',
    address: 'BTP Blok AE No. 60',
    description: 'Gamis syar\'i, jilbab instan, mukena katun jepang, dan kaos kaki wudhu. Produksi konveksi mandiri keluarga jamaah.',
    products: ['Gamis Syar\'i Polos', 'Mukena Dewasa Katun', 'Khimar Ceruty 2 Layer'],
    priceRange: 'Rp 35.000 - Rp 220.000',
    bazarParticipant: true,
    qardhFacility: {
      hasLoan: true,
      loanAmount: 7500000,
      disbursedDate: '2026-05-15',
      remainingAmount: 4500000,
      monthlyInstallment: 625000,
      status: 'LANCAR',
    },
    verifiedByDkm: true,
  },
  {
    id: 'umkm-003',
    name: 'Herbal & Madu Murni Habbatussauda BTP',
    category: 'HERBAL_KESEHATAN',
    ownerName: 'Pak Wahyu Hidayat',
    phone: '0822-4466-8800',
    rt: 'RT 03',
    address: 'BTP Blok AE No. 51',
    description: 'Penyedia thibbun nabawi terpercaya: Madu Hutan Sumbawa murni, Minyak Zaitun Extra Virgin, Kapsul Habbatussauda, dan Bekam Steril panggilan.',
    products: ['Madu Hutan 500g', 'Minyak Habbatussauda Softgel', 'Minyak Zaitun Ruqyah'],
    priceRange: 'Rp 45.000 - Rp 150.000',
    bazarParticipant: false,
    qardhFacility: {
      hasLoan: false,
      loanAmount: 0,
      remainingAmount: 0,
      monthlyInstallment: 0,
      status: 'BEBAS_PINJAMAN',
    },
    verifiedByDkm: true,
  },
  {
    id: 'umkm-004',
    name: 'Kios Sembako & Isi Ulang Galon Berkah RW',
    category: 'SEMBAKO_KONTRAKAN',
    ownerName: 'Pak Amiruddin (Satpam RW)',
    phone: '0852-1133-5577',
    rt: 'RT 04',
    address: 'Samping Pos Satpam Blok AE',
    description: 'Warung sembako warga melayani kebutuhan beras Ramos, telur, gas elpiji 3kg, dan air isi ulang RO higienis siap antar lorong.',
    products: ['Beras Ramos 5kg', 'Air Galon RO Antar Rumah', 'Gas Elpiji 3kg'],
    priceRange: 'Rp 6.000 - Rp 80.000',
    bazarParticipant: true,
    qardhFacility: {
      hasLoan: true,
      loanAmount: 3000000,
      disbursedDate: '2026-07-01',
      remainingAmount: 2000000,
      monthlyInstallment: 250000,
      status: 'LANCAR',
    },
    verifiedByDkm: true,
  },
  {
    id: 'umkm-005',
    name: 'Studio Desain Grafis & Percetakan Undangan IRMA',
    category: 'JASA_KREATIF',
    ownerName: 'Fikri Haikal (Ketua IRMA)',
    phone: '0852-9988-1122',
    rt: 'RT 01',
    address: 'BTP Blok AE No. 10',
    description: 'Jasa desain grafis spanduk dakwah, cetak kartu nama, stiker kemasan UMKM, banner, dan undangan pernikahan syar\'i.',
    products: ['Cetak Stiker Label UMKM', 'Desain Banner Acara', 'Undangan Digital Web'],
    priceRange: 'Rp 15.000 - Rp 250.000',
    bazarParticipant: false,
    qardhFacility: {
      hasLoan: false,
      loanAmount: 0,
      remainingAmount: 0,
      monthlyInstallment: 0,
      status: 'BEBAS_PINJAMAN',
    },
    verifiedByDkm: true,
  },
];
