import { ProgramKerjaItem } from '@/types/program-kerja';

export const OFFICIAL_PROGRAM_KERJA: ProgramKerjaItem[] = [
  // ==========================================================================
  // 1. SEKSI PERIBADATAN & DAKWAH (KOMISI I)
  // ==========================================================================
  {
    id: 'pk-001',
    code: 'PK-IBD-01',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PERIBADATAN_DAKWAH',
    seksiName: 'Seksi Peribadatan & Dakwah',
    title: 'Penetapan Standar Honorarium 3 Imam Sholat Rawatib',
    description: 'Penyaluran insentif rutin bulanan sebesar Rp 1.500.000/imam per bulan untuk menjaga ketertiban 5 waktu sholat fardhu.',
    pic: 'Drs. Manai, M.M.',
    allocatedBudget: 54000000,
    targetTimeline: 'Januari - Desember 2026',
    targetDate: '2026-12-31',
    rakerStatus: 'DIREVISI',
    executionStatus: 'BERJALAN',
    progressPercent: 75,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-01',
    notes: 'Disetujui revisi kenaikan honor dari Rp1jt ke Rp1.5jt di Raker pleno.',
    budgetProgramId: 'bg-001',
  },
  {
    id: 'pk-002',
    code: 'PK-IBD-02',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PERIBADATAN_DAKWAH',
    seksiName: 'Seksi Peribadatan & Dakwah',
    title: 'Penyusunan & Pengelolaan Jadwal 52 Pekan Khatib Jumat',
    description: 'Penyusunan jadwal khatib tahunan, pengiriman surat tugas resmi H-3, serta konfirmasi kehadiran via WhatsApp.',
    pic: 'Ust. Haris, S.Pd.I',
    allocatedBudget: 28800000,
    targetTimeline: 'Tahun Berjalan 2026',
    targetDate: '2026-12-31',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 70,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-05',
    notes: 'Database 20 khatib tetap telah terintegrasi di modul dakwah.',
    budgetProgramId: 'bg-002',
  },
  {
    id: 'pk-003',
    code: 'PK-IBD-03',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PERIBADATAN_DAKWAH',
    seksiName: 'Seksi Peribadatan & Dakwah',
    title: 'Pengadaan & Instalasi Timer Ampli Otomatis Adzan',
    description: 'Pemasangan perangkat otomatisasi saklar ampli adzan untuk menjamin ketepatan waktu kumandang adzan.',
    pic: 'Bambang Sudarmono',
    allocatedBudget: 500000,
    targetTimeline: 'Agustus 2026',
    targetDate: '2026-08-25',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'SELESAI',
    progressPercent: 100,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-28',
    notes: 'Perangkat telah terpasang dan berfungsi optimal di ruang audio.',
    budgetProgramId: 'bg-003',
  },
  {
    id: 'pk-004',
    code: 'PK-IBD-04',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PERIBADATAN_DAKWAH',
    seksiName: 'Seksi Peribadatan & Dakwah',
    title: 'Penyelenggaraan Kajian Rutin Ahad Subuh & Dhuha',
    description: 'Kajian tematik fiqih ibadah dan tafsir Al-Quran bekerja sama dengan dai Kota Makassar (maksimal 2x/pekan).',
    pic: 'Drs. Manai, M.M.',
    allocatedBudget: 22800000,
    targetTimeline: 'Sepanjang Tahun 2026',
    targetDate: '2026-12-31',
    rakerStatus: 'DIREVISI',
    executionStatus: 'BERJALAN',
    progressPercent: 65,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-02',
    notes: 'Didanai swadaya jamaah tanpa membebani kas rutin operasional.',
    budgetProgramId: 'bg-004',
  },
  {
    id: 'pk-005',
    code: 'PK-IBD-05',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PERIBADATAN_DAKWAH',
    seksiName: 'Seksi Peribadatan & Dakwah',
    title: 'Pelaksanaan Tahsin & Tahfidz Jamaah Dewasa',
    description: 'Bimbingan makharijul huruf dan tajwid Al-Qur\'an setiap malam Rabu ba\'da Maghrib.',
    pic: 'Ust. Haris, S.Pd.I',
    allocatedBudget: 6000000,
    targetTimeline: 'Mulai Juli 2026',
    targetDate: '2026-11-30',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 50,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-30',
    notes: 'Diikuti oleh 28 jamaah aktif RT 01 - 05.',
  },
  {
    id: 'pk-006',
    code: 'PK-IBD-06',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PERIBADATAN_DAKWAH',
    seksiName: 'Seksi Peribadatan & Dakwah',
    title: 'Peringatan Maulid Nabi Muhammad SAW 1448 H',
    description: 'Penyelenggaraan tabligh akbar maulid nabi dengan pembentukan panitia pelaksana terpadu.',
    pic: 'Drs. Manai, M.M.',
    allocatedBudget: 3250000,
    targetTimeline: 'September 2026',
    targetDate: '2026-09-18',
    rakerStatus: 'DIREVISI',
    executionStatus: 'BERJALAN',
    progressPercent: 60,
    trafficLight: 'KUNING',
    lastUpdate: '2026-09-04',
    notes: 'Proposal sponsorship telah disebarkan; menunggu pencairan dana swadaya.',
    budgetProgramId: 'bg-005',
  },
  {
    id: 'pk-007',
    code: 'PK-IBD-07',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PERIBADATAN_DAKWAH',
    seksiName: 'Seksi Peribadatan & Dakwah',
    title: 'Karantina Tahfidz Ramadhan & I\'tikaf 10 Malam Terakhir',
    description: 'Penyelenggaraan sahur bersama dan fasilitasi i\'tikaf untuk 100 jamaah di sepuluh malam penutup Ramadhan.',
    pic: 'Ust. Haris, S.Pd.I',
    allocatedBudget: 18000000,
    targetTimeline: 'Ramadhan 1448 H',
    targetDate: '2027-03-25',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 0,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-20',
    notes: 'Menunggu kalender Hijriah mendekati Rajab 1448 H.',
  },
  {
    id: 'pk-008',
    code: 'PK-IBD-08',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PERIBADATAN_DAKWAH',
    seksiName: 'Seksi Peribadatan & Dakwah',
    title: 'Penyusunan Risalah Khutbah & Buletin Jumat Masjid',
    description: 'Penerbitan lembaran buletin dakwah cetak 4 halaman yang dibagikan kepada jamaah sholat Jumat.',
    pic: 'Sekretariat Dakwah',
    allocatedBudget: 4800000,
    targetTimeline: 'Oktober 2026 - Desember 2027',
    targetDate: '2026-10-15',
    rakerStatus: 'DIREVISI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 10,
    trafficLight: 'KUNING',
    lastUpdate: '2026-08-15',
    notes: 'Perlu penetapan tim redaksi naskah.',
  },
  {
    id: 'pk-009',
    code: 'PK-IBD-09',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PERIBADATAN_DAKWAH',
    seksiName: 'Seksi Peribadatan & Dakwah',
    title: 'Pelatihan Pengurusan Jenazah Syar\'i (Fardhu Kifayah)',
    description: 'Workshop pemandian, pengafanan, dan sholat jenazah untuk 40 warga perwakilan RT 01-05.',
    pic: 'Drs. Manai, M.M.',
    allocatedBudget: 2500000,
    targetTimeline: 'November 2026',
    targetDate: '2026-11-20',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 0,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-24',
    notes: 'Narasumber dari MUI Kota Makassar telah dikontak.',
  },

  // ==========================================================================
  // 2. SEKSI PENDIDIKAN & REMAJA (KOMISI I)
  // ==========================================================================
  {
    id: 'pk-010',
    code: 'PK-PDK-01',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PENDIDIKAN_REMAJA',
    seksiName: 'Seksi Pendidikan & Remaja',
    title: 'Revitalisasi Pengurus Ikatan Remaja Masjid (IRMA) Babul Khaer',
    description: 'Musyawarah pemilihan ketua baru dan penyusunan struktur keorganisasian remaja masjid.',
    pic: 'Ahmad Fauzi & Tim IRMA',
    allocatedBudget: 3500000,
    targetTimeline: 'Agustus - September 2026',
    targetDate: '2026-09-25',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 80,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-03',
    notes: 'Draf calon pengurus telah diajukan ke Ketua Umum.',
  },
  {
    id: 'pk-011',
    code: 'PK-PDK-02',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PENDIDIKAN_REMAJA',
    seksiName: 'Seksi Pendidikan & Remaja',
    title: 'Pelatihan Kepemimpinan & Manajemen Organisasi Remaja',
    description: 'Latihan dasar kepemimpinan (LDK) Islami untuk 35 pemuda Kompleks BTP Blok AE.',
    pic: 'Koordinator Pendidikan',
    allocatedBudget: 15000000,
    targetTimeline: 'Oktober 2026',
    targetDate: '2026-10-28',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 30,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-29',
    notes: 'Sesuai ketetapan Raker, dilarang membuka kotak amal terpisah khusus remaja.',
    budgetProgramId: 'bg-006',
  },
  {
    id: 'pk-012',
    code: 'PK-PDK-03',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PENDIDIKAN_REMAJA',
    seksiName: 'Seksi Pendidikan & Remaja',
    title: 'Pekan Olahraga & Seni Islam (PORSENI) Antar Lorong',
    description: 'Pertandingan futsal sarung, tenis meja, dan adzan/tilawah antar-RT menyambut Tahun Baru Hijriah.',
    pic: 'Ketua IRMA',
    allocatedBudget: 5000000,
    targetTimeline: 'Desember 2026',
    targetDate: '2026-12-20',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 0,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-25',
    notes: 'Akan memanfaatkan pelataran masjid dan aula serbaguna.',
  },
  {
    id: 'pk-013',
    code: 'PK-PDK-04',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PENDIDIKAN_REMAJA',
    seksiName: 'Seksi Pendidikan & Remaja',
    title: 'Klinik Belajar Gratis Siswa Dhuafa (Bimbel SD/SMP)',
    description: 'Bantuan bimbingan belajar matematika dan bahasa Inggris gratis tiap Sabtu pagi.',
    pic: 'Relawan Mahasiswa Unhas',
    allocatedBudget: 2400000,
    targetTimeline: 'Mulai Oktober 2026',
    targetDate: '2026-10-10',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 20,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-01',
    notes: 'Merekrut 6 mahasiswa binaan jamaah sebagai mentor.',
  },
  {
    id: 'pk-014',
    code: 'PK-PDK-05',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PENDIDIKAN_REMAJA',
    seksiName: 'Seksi Pendidikan & Remaja',
    title: 'Pemberdayaan Marbot Muda & Pelatihan Teknisi Audio',
    description: 'Pelatihan mixing sound system dan perawatan amplifier untuk marbot dan pemuda masjid.',
    pic: 'Bambang Sudarmono',
    allocatedBudget: 1500000,
    targetTimeline: 'September 2026',
    targetDate: '2026-09-30',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 40,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-03',
    notes: 'Dua orang marbot telah mulai magang teknisi.',
  },
  {
    id: 'pk-015',
    code: 'PK-PDK-06',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PENDIDIKAN_REMAJA',
    seksiName: 'Seksi Pendidikan & Remaja',
    title: 'Ekstrakurikuler Panahan & Seni Bela Diri Santri',
    description: 'Latihan panahan tradisional dan tapak suci di halaman masjid setiap Ahad pagi.',
    pic: 'PJ Remaja',
    allocatedBudget: 3000000,
    targetTimeline: 'November 2026',
    targetDate: '2026-11-15',
    rakerStatus: 'DITUNDA',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 0,
    trafficLight: 'KUNING',
    lastUpdate: '2026-08-20',
    notes: 'Ditunda menunggu penyelesaian penataan paving pelataran parkir.',
  },
  {
    id: 'pk-016',
    code: 'PK-PDK-07',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PENDIDIKAN_REMAJA',
    seksiName: 'Seksi Pendidikan & Remaja',
    title: 'Kajian Pemuda Hijrah "Coffee Night & Sharing Session"',
    description: 'Kajian santai bulanan membahas problematika pergaulan pemuda, narkoba, dan kewirausahaan.',
    pic: 'Ketua IRMA',
    allocatedBudget: 3600000,
    targetTimeline: 'Sepanjang 2026-2027',
    targetDate: '2026-12-15',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 50,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-02',
    notes: 'Edisi pertama sukses dihadiri 45 peserta muda.',
  },
  {
    id: 'pk-017',
    code: 'PK-PDK-08',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiId: 'PENDIDIKAN_REMAJA',
    seksiName: 'Seksi Pendidikan & Remaja',
    title: 'Pengadaan Sudut Baca & Pojok Literasi Digital Islam',
    description: 'Penyediaan rak buku keislaman dan akses tablet e-library di serambi selatan masjid.',
    pic: 'Ahmad Fauzi',
    allocatedBudget: 4500000,
    targetTimeline: 'November 2026',
    targetDate: '2026-11-10',
    rakerStatus: 'DIREVISI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 15,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-25',
    notes: 'Koleksi 120 buku wakaf telah terkumpul.',
  },

  // ==========================================================================
  // 3. SEKSI PEMBANGUNAN (KOMISI II)
  // ==========================================================================
  {
    id: 'pk-020',
    code: 'PK-PBG-01',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'PEMBANGUNAN',
    seksiName: 'Seksi Pembangunan',
    title: 'Renovasi Plafon Gypsum Ruang Sholat Lantai 2',
    description: 'Pembongkaran dan penggantian rangka hollow galvanis plafon lantai 2 seluas 350 m2 untuk mencegah kebocoran.',
    pic: 'H. Muh. Nancha Pattanang, S.E.',
    allocatedBudget: 350000000,
    targetTimeline: 'Oktober 2026 - Februari 2027',
    targetDate: '2027-02-28',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 35,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-05',
    notes: 'RAB teknis final selesai; menunggu pencairan termin I donatur khusus.',
    budgetProgramId: 'bg-010',
  },
  {
    id: 'pk-021',
    code: 'PK-PBG-02',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'PEMBANGUNAN',
    seksiName: 'Seksi Pembangunan',
    title: 'Mega Proyek Pembangunan Menara Masjid (Tinggi 30 Meter)',
    description: 'Pembangunan struktur beton bertulang tiang pancang menara utama ikon masjid beserta kubah menara.',
    pic: 'Panitia Pembangunan Menara (H. Arifin)',
    allocatedBudget: 1550000000,
    targetTimeline: '2026 - 2028 (Multiyears)',
    targetDate: '2028-06-30',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 20,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-04',
    notes: 'Pengurusan IMB & uji sondir tanah telah rampung; lelang kontraktor.',
    budgetProgramId: 'bg-011',
  },
  {
    id: 'pk-022',
    code: 'PK-PBG-03',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'PEMBANGUNAN',
    seksiName: 'Seksi Pembangunan',
    title: 'Perbaikan Sistem Drainase, Pelataran Parkir & Wudhu Tiap Gerbang',
    description: 'Pemasangan gorong-gorong U-Ditch 40 cm di sisi timur dan penataan kran wudhu gerbang barat.',
    pic: 'Ir. Ruslan Effendi',
    allocatedBudget: 150000000,
    targetTimeline: 'September - Desember 2026',
    targetDate: '2026-12-15',
    rakerStatus: 'DIREVISI',
    executionStatus: 'BERJALAN',
    progressPercent: 45,
    trafficLight: 'KUNING',
    lastUpdate: '2026-09-02',
    notes: 'Material pipa paralon dan semen telah tiba di lokasi.',
    budgetProgramId: 'bg-012',
  },
  {
    id: 'pk-023',
    code: 'PK-PBG-04',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'PEMBANGUNAN',
    seksiName: 'Seksi Pembangunan',
    title: 'Pemasangan Kanopi Polikarbonat Pelataran Sayap Kiri & Kanan',
    description: 'Pemasangan atap kanopi baja ringan untuk memperluas kapasitas tampung sholat Jumat dari terik matahari dan hujan.',
    pic: 'Ir. Ruslan Effendi',
    allocatedBudget: 85000000,
    targetTimeline: 'Januari 2027',
    targetDate: '2027-01-31',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 0,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-20',
    notes: 'Menunggu rekomendasi gambar arsitektur.',
  },
  {
    id: 'pk-024',
    code: 'PK-PBG-05',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'PEMBANGUNAN',
    seksiName: 'Seksi Pembangunan',
    title: 'Renovasi Toilet Khusus Difabel & Lansia',
    description: 'Pembuatan 2 bilik toilet ramah lansia dengan handrail stainless steel dan kloset duduk ergonomis.',
    pic: 'Bambang Sudarmono',
    allocatedBudget: 25000000,
    targetTimeline: 'Oktober 2026',
    targetDate: '2026-10-31',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 55,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-01',
    notes: 'Pemasangan keramik dinding dan sanitair sedang dikerjakan.',
  },
  {
    id: 'pk-025',
    code: 'PK-PBG-06',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'PEMBANGUNAN',
    seksiName: 'Seksi Pembangunan',
    title: 'Pengecatan Ulang Eksterior Kubah & Dinding Luar',
    description: 'Pengecatan ulang cat weatherproof anti-jamur pada kubah utama warna hijau zamrud dan lis ornamen putih.',
    pic: 'H. Muh. Nancha Pattanang, S.E.',
    allocatedBudget: 45000000,
    targetTimeline: 'November 2026',
    targetDate: '2026-11-30',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 10,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-27',
    notes: 'Penyewaan scaffolding 4 tingkat telah disurvei.',
  },
  {
    id: 'pk-026',
    code: 'PK-PBG-07',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'PEMBANGUNAN',
    seksiName: 'Seksi Pembangunan',
    title: 'Peningkatan Pagar Pembatas & Gerbang Otomatis Kompleks',
    description: 'Peninggian pagar besi pembatas barat setinggi 2 meter dan instalasi pintu dorong pengaman.',
    pic: 'Koordinator Keamanan',
    allocatedBudget: 32000000,
    targetTimeline: 'Desember 2026',
    targetDate: '2026-12-25',
    rakerStatus: 'DIREVISI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 0,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-18',
    notes: 'Dikoordinasikan dengan pengurus RW 08.',
  },
  {
    id: 'pk-027',
    code: 'PK-PBG-08',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'PEMBANGUNAN',
    seksiName: 'Seksi Pembangunan',
    title: 'Pemasangan Panel Surya (Solar Cell) Penerangan Malam',
    description: 'Pemasangan 6 unit lampu PJU solar cell 100W mandiri untuk area parkir dan gang samping masjid.',
    pic: 'Bambang Sudarmono',
    allocatedBudget: 18000000,
    targetTimeline: 'Februari 2027',
    targetDate: '2027-02-20',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 0,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-25',
    notes: 'Ditargetkan menghemat beban tagihan listrik PLN bulanan.',
  },

  // ==========================================================================
  // 4. SEKSI SARANA & PRASARANA (KOMISI II)
  // ==========================================================================
  {
    id: 'pk-030',
    code: 'PK-SAR-01',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'SARANA_PRASARANA',
    seksiName: 'Seksi Sarana & Prasarana',
    title: 'Pengadaan & Pemasangan 2 Unit AC Standing Daikin 5 PK',
    description: 'Pemasangan pendingin ruangan standing floor untuk kenyamanan sholat berjamaah di shaf depan dan mimbar.',
    pic: 'Bambang Sudarmono',
    allocatedBudget: 27000000,
    targetTimeline: 'Juli 2026',
    targetDate: '2026-07-20',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'SELESAI',
    progressPercent: 100,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-07-25',
    notes: '2 unit AC duduk Daikin standing floor telah beroperasi penuh.',
    budgetProgramId: 'bg-013',
  },
  {
    id: 'pk-031',
    code: 'PK-SAR-02',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'SARANA_PRASARANA',
    seksiName: 'Seksi Sarana & Prasarana',
    title: 'Pemasangan Modul Otomatis ATS & Relokasi Genset Silent',
    description: 'Pemindahan ruang mesin genset ke sudut timur dan pemasangan Automatic Transfer Switch (ATS) 10 kVA.',
    pic: 'Bambang Sudarmono',
    allocatedBudget: 3500000,
    targetTimeline: 'Agustus 2026',
    targetDate: '2026-08-30',
    rakerStatus: 'DIREVISI',
    executionStatus: 'TERLAMBAT',
    progressPercent: 60,
    trafficLight: 'MERAH',
    lastUpdate: '2026-08-20',
    notes: 'ALERT: Melewati tenggat 30 Agustus 2026, modul ATS impor tertunda pengiriman vendor.',
    budgetProgramId: 'bg-014',
  },
  {
    id: 'pk-032',
    code: 'PK-SAR-03',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'SARANA_PRASARANA',
    seksiName: 'Seksi Sarana & Prasarana',
    title: 'Pengadaan Komputer & Printer Kantor Sekretariat DKM',
    description: 'Satu set PC Core i5, monitor 24 inci, dan printer scan all-in-one Epson L3210 untuk kelancaran persuratan dinas.',
    pic: 'Sekretariat DKM',
    allocatedBudget: 15000000,
    targetTimeline: 'September 2026',
    targetDate: '2026-09-15',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 40,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-02',
    notes: 'Menunggu survei harga 3 toko komputer di Makassar.',
    budgetProgramId: 'bg-015',
  },
  {
    id: 'pk-033',
    code: 'PK-SAR-04',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'SARANA_PRASARANA',
    seksiName: 'Seksi Sarana & Prasarana',
    title: 'Servis Berkala & Pembersihan Filter 6 Unit AC Per 3 Bulan',
    description: 'Pembersihan evaporator, pembersihan filter udara, dan pengisian freon R32 rutin seluruh AC ruang sholat.',
    pic: 'Bambang Sudarmono',
    allocatedBudget: 3600000,
    targetTimeline: 'September, Desember 2026, Maret 2027',
    targetDate: '2026-09-10',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 70,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-05',
    notes: 'Teknisi dijadwalkan servis sebelum pekan ke-2 September.',
  },
  {
    id: 'pk-034',
    code: 'PK-SAR-05',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'SARANA_PRASARANA',
    seksiName: 'Seksi Sarana & Prasarana',
    title: 'Pengadaan 4 Unit Mikrofon Nirkabel UHF & Penggantian Baterai Charge',
    description: 'Pembaruan mic wireless imam dan adzan untuk menghilangkan gangguan frekuensi/interferensi gelombang.',
    pic: 'Bambang Sudarmono',
    allocatedBudget: 4200000,
    targetTimeline: 'Oktober 2026',
    targetDate: '2026-10-15',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 0,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-25',
    notes: 'Merek Shure BLX24 direkomendasikan teknisi audio.',
  },
  {
    id: 'pk-035',
    code: 'PK-SAR-06',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'SARANA_PRASARANA',
    seksiName: 'Seksi Sarana & Prasarana',
    title: 'Cuci Karpet & Sterilisasi Ruang Sholat Utama',
    description: 'Jasa pencucian karpet tebal turki 40 shaf dengan mesin ekstraktor dan disinfeksi aromaterapi mawar.',
    pic: 'Marbot Firman & Bambang',
    allocatedBudget: 6500000,
    targetTimeline: 'November 2026 (Menjelang Ramadhan)',
    targetDate: '2026-11-25',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 0,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-20',
    notes: 'Pekerjaan dilaksanakan saat jeda sholat Isya ke Subuh.',
  },
  {
    id: 'pk-036',
    code: 'PK-SAR-07',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'SARANA_PRASARANA',
    seksiName: 'Seksi Sarana & Prasarana',
    title: 'Pemasangan Smart CCTV 12 Titik dengan Perekaman Cloud & NVR',
    description: 'Pemasangan kamera pengawas beresolusi 4MP di gerbang, kotak amal, ruang sound, dan batas saf wanita.',
    pic: 'Bambang Sudarmono',
    allocatedBudget: 14500000,
    targetTimeline: 'Oktober 2026',
    targetDate: '2026-10-20',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 40,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-03',
    notes: '8 unit kamera telah terpasang; kabel jaringan LAN siap.',
  },
  {
    id: 'pk-037',
    code: 'PK-SAR-08',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'SARANA_PRASARANA',
    seksiName: 'Seksi Sarana & Prasarana',
    title: 'Penggantian Pompa Air Otomatis Booster Pump Tempat Wudhu',
    description: 'Pemasangan pompa dorong Shimizu 250W agar debit pancuran wudhu lantai 1 dan 2 mengalir deras merata.',
    pic: 'Marbot Firman',
    allocatedBudget: 2800000,
    targetTimeline: 'Agustus 2026',
    targetDate: '2026-08-15',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'SELESAI',
    progressPercent: 100,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-18',
    notes: 'Pompa booster baru telah terpasang di toren penampungan.',
  },
  {
    id: 'pk-038',
    code: 'PK-SAR-09',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'SARANA_PRASARANA',
    seksiName: 'Seksi Sarana & Prasarana',
    title: 'Digitalisasi Label Barcode QR Seluruh Aset Inventaris Fisik',
    description: 'Pemasangan stiker label kode QR tahan air pada 45 item inventaris utama masjid.',
    pic: 'Bambang Sudarmono',
    allocatedBudget: 750000,
    targetTimeline: 'September 2026',
    targetDate: '2026-09-20',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 65,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-04',
    notes: 'Terhubung dengan modul inventaris sarpras SIK-MBH.',
  },

  // ==========================================================================
  // 5. SEKSI HUMAS & SOSIAL KEMASYARAKATAN (KOMISI SOSIAL/HUMAS)
  // ==========================================================================
  {
    id: 'pk-040',
    code: 'PK-HUM-01',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & Humas',
    seksiId: 'HUMAS_SOSIAL',
    seksiName: 'Seksi Humas & Sosial Kemasyarakatan',
    title: 'Sensus Pendataan Profil Jamaah & KK RT 01 - 05 Blok AE',
    description: 'Pemutakhiran basis data kependudukan jamaah meliputi status ekonomi, profesi, dan kontak darurat.',
    pic: 'Drs. H. Suardi, M.Pd.',
    allocatedBudget: 4500000,
    targetTimeline: 'Juli - September 2026',
    targetDate: '2026-09-30',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 85,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-05',
    notes: 'Tercatat 163 KK dan 450+ jiwa jamaah terverifikasi di sistem.',
  },
  {
    id: 'pk-041',
    code: 'PK-HUM-02',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & Humas',
    seksiId: 'HUMAS_SOSIAL',
    seksiName: 'Seksi Humas & Sosial Kemasyarakatan',
    title: 'Pelaksanaan Program Gerakan Sedekah Seribu Sehari (SSS)',
    description: 'Distribusi dan penarikan berkala 100 kaleng koin sedekah SSS di rumah-rumah warga RT 01-05.',
    pic: 'Ust. Rahman & Tim Humas',
    allocatedBudget: 30000000,
    targetTimeline: 'Rutin Setiap Bulan',
    targetDate: '2026-12-31',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 70,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-04',
    notes: 'Realisasi kas terkumpul telah mencapai Rp12,3 juta.',
    budgetProgramId: 'bg-020',
  },
  {
    id: 'pk-042',
    code: 'PK-HUM-03',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & Humas',
    seksiId: 'HUMAS_SOSIAL',
    seksiName: 'Seksi Humas & Sosial Kemasyarakatan',
    title: 'Penyelenggaraan Santunan Duka & Layanan Mobil Jenazah Jamaah',
    description: 'Pemberian uang duka Rp 500.000 bagi keluarga jamaah yang wafat dan koordinasi ambulance gratis.',
    pic: 'Koordinator Sosial',
    allocatedBudget: 12000000,
    targetTimeline: 'Sepanjang Tahun 2026',
    targetDate: '2026-12-31',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 50,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-31',
    notes: 'Telah disalurkan kepada 4 ahli waris jamaah.',
  },
  {
    id: 'pk-043',
    code: 'PK-HUM-04',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & Humas',
    seksiId: 'HUMAS_SOSIAL',
    seksiName: 'Seksi Humas & Sosial Kemasyarakatan',
    title: 'Penerbitan Majalah Dinding & Akun Media Sosial Resmi Masjid',
    description: 'Pengelolaan akun Instagram, YouTube siaran langsung kajian, dan grup WhatsApp resmi jamaah.',
    pic: 'Humas DKM',
    allocatedBudget: 1800000,
    targetTimeline: 'Tahun 2026',
    targetDate: '2026-12-31',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 75,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-02',
    notes: 'Instagram @masjidbabulkhaer aktif menyiarkan jadwal sholat.',
  },
  {
    id: 'pk-044',
    code: 'PK-HUM-05',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & Humas',
    seksiId: 'HUMAS_SOSIAL',
    seksiName: 'Seksi Humas & Sosial Kemasyarakatan',
    title: 'Silaturahmi Rutin & Musyawarah Koordinasi dengan Ketua RT/RW',
    description: 'Pertemuan triwulanan bersama ketua RT 01-05 dan RW 08 untuk sinergi keamanan dan kebersihan lingkungan.',
    pic: 'H. Arifin & Sekretaris',
    allocatedBudget: 2000000,
    targetTimeline: 'September & Desember 2026',
    targetDate: '2026-09-28',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 40,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-25',
    notes: 'Surat undangan pertemuan September sedang disiapkan.',
  },
  {
    id: 'pk-045',
    code: 'PK-HUM-06',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & Humas',
    seksiId: 'HUMAS_SOSIAL',
    seksiName: 'Seksi Humas & Sosial Kemasyarakatan',
    title: 'Bakti Sosial & Pemeriksaan Kesehatan Gratis Lansia Jamaah',
    description: 'Cek tensi, gula darah, dan konsultasi dokter umum gratis bekerja sama dengan Puskesmas Tamalanrea.',
    pic: 'Seksi Sosial Kemasyarakatan',
    allocatedBudget: 6000000,
    targetTimeline: 'Oktober 2026',
    targetDate: '2026-10-18',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 25,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-29',
    notes: 'Target 80 lansia di wilayah BTP Blok AE.',
  },
  {
    id: 'pk-046',
    code: 'PK-HUM-07',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & Humas',
    seksiId: 'HUMAS_SOSIAL',
    seksiName: 'Seksi Humas & Sosial Kemasyarakatan',
    title: 'Penyaluran Paket Sembako Jumat Berkah Dhuafa',
    description: 'Pemberian paket beras 5kg, minyak goreng, dan telur untuk 25 dhuafa lansia setiap Jumat pertama.',
    pic: 'Ust. Rahman',
    allocatedBudget: 15000000,
    targetTimeline: 'Setiap Bulan',
    targetDate: '2026-12-31',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 65,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-04',
    notes: 'Menggunakan alokasi dana swadaya donatur Jumat.',
  },
  {
    id: 'pk-047',
    code: 'PK-HUM-08',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & Humas',
    seksiId: 'HUMAS_SOSIAL',
    seksiName: 'Seksi Humas & Sosial Kemasyarakatan',
    title: 'Pengadaan Papan Informasi & Running Text Digital Outdoor',
    description: 'Pemasangan display LED running text jadwal sholat dan pengumuman kegiatan di pagar utama masjid.',
    pic: 'Humas & Sarpras',
    allocatedBudget: 8000000,
    targetTimeline: 'November 2026',
    targetDate: '2026-11-30',
    rakerStatus: 'DIREVISI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 10,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-22',
    notes: 'Spesifikasi teknis P10 outdoor tahan hujan.',
  },

  // ==========================================================================
  // 6. SEKSI ZISWAF & PEMBERDAYAAN MUSTAHIQ (KOMISI SOSIAL/HUMAS)
  // ==========================================================================
  {
    id: 'pk-050',
    code: 'PK-ZIS-01',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & ZISWAF',
    seksiId: 'ZISWAF_MUSTAHIQ',
    seksiName: 'Seksi ZISWAF & Pemberdayaan Mustahiq',
    title: 'Pembentukan & Penetapan Panitia UPZ (Unit Pengumpul Zakat) DKM',
    description: 'Penerbitan SK Kepengurusan UPZ resmi DKM Babul Khaer dan penetapan loket amil zakat.',
    pic: 'Ust. Rahman & H. Sahali',
    allocatedBudget: 2000000,
    targetTimeline: 'Agustus - September 2026',
    targetDate: '2026-09-20',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 75,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-03',
    notes: 'Susunan pengurus 5 orang telah disahkan Ketua Umum.',
  },
  {
    id: 'pk-051',
    code: 'PK-ZIS-02',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & ZISWAF',
    seksiId: 'ZISWAF_MUSTAHIQ',
    seksiName: 'Seksi ZISWAF & Pemberdayaan Mustahiq',
    title: 'Pengajuan Legalitas Registrasi UPZ ke BAZNAS Kota Makassar',
    description: 'Penyerahan berkas AD/ART, SK Pengurus DKM, dan permohonan nomor register resmi UPZ BAZNAS.',
    pic: 'Ahmad Fauzi & Ust. Rahman',
    allocatedBudget: 1500000,
    targetTimeline: 'September 2026',
    targetDate: '2026-09-25',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 50,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-04',
    notes: 'Dokumen pengantar telah diterima staf sekretariat BAZNAS.',
  },
  {
    id: 'pk-052',
    code: 'PK-ZIS-03',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & ZISWAF',
    seksiId: 'ZISWAF_MUSTAHIQ',
    seksiName: 'Seksi ZISWAF & Pemberdayaan Mustahiq',
    title: 'Sensus Pemetaan 8 Asnaf Mustahiq RT 01 - 05 Blok AE',
    description: 'Verifikasi lapangan kondisi ekonomi keluarga miskin, fakir, lansia sebatang kara, dan anak yatim.',
    pic: 'Ust. Rahman',
    allocatedBudget: 2500000,
    targetTimeline: 'Agustus 2026',
    targetDate: '2026-08-30',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'SELESAI',
    progressPercent: 100,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-31',
    notes: 'Tercatat 27 kepala keluarga mustahiq prioritas penerima bantuan.',
  },
  {
    id: 'pk-053',
    code: 'PK-ZIS-04',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & ZISWAF',
    seksiId: 'ZISWAF_MUSTAHIQ',
    seksiName: 'Seksi ZISWAF & Pemberdayaan Mustahiq',
    title: 'Penyaluran Beasiswa Pendidikan Santri Dhuafa & Yatim',
    description: 'Bantuan biaya SPP dan perlengkapan sekolah untuk 15 anak yatim dan dhuafa di lingkungan sekitar.',
    pic: 'H. Sahali & Ust. Rahman',
    allocatedBudget: 18000000,
    targetTimeline: 'Tiap Semester (Juli & Januari)',
    targetDate: '2026-12-31',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 60,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-01',
    notes: 'Termin semester ganjil telah disalurkan tunai Rp4,5jt.',
  },
  {
    id: 'pk-054',
    code: 'PK-ZIS-05',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & ZISWAF',
    seksiId: 'ZISWAF_MUSTAHIQ',
    seksiName: 'Seksi ZISWAF & Pemberdayaan Mustahiq',
    title: 'Pengembangan Database Muzakki & Kanal Zakat Digital',
    description: 'Pencatatan data jamaah pembayar zakat mal dan fitrah terintegrasi dengan kode unik transfer rekening BSI DKM.',
    pic: 'Ahmad Fauzi',
    allocatedBudget: 1000000,
    targetTimeline: 'September 2026',
    targetDate: '2026-09-30',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 60,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-05',
    notes: 'Fitur pendataan Muzakki sedang diintegrasikan ke SIK-MBH.',
  },
  {
    id: 'pk-055',
    code: 'PK-ZIS-06',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & ZISWAF',
    seksiId: 'ZISWAF_MUSTAHIQ',
    seksiName: 'Seksi ZISWAF & Pemberdayaan Mustahiq',
    title: 'Penyusunan Format Laporan Rekonsiliasi Standar BAZNAS',
    description: 'Penerapan standar akuntansi zakat PSAK 109 dan format pelaporan berkala triwulanan ke BAZNAS.',
    pic: 'H. Sahali',
    allocatedBudget: 1200000,
    targetTimeline: 'Oktober 2026',
    targetDate: '2026-10-15',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 40,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-02',
    notes: 'Template ekspor Excel BAZNAS sedang disiapkan.',
  },
  {
    id: 'pk-056',
    code: 'PK-ZIS-07',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & ZISWAF',
    seksiId: 'ZISWAF_MUSTAHIQ',
    seksiName: 'Seksi ZISWAF & Pemberdayaan Mustahiq',
    title: 'Pelaksanaan Qurban Idul Adha 1448 H & Distribusi Daging',
    description: 'Penyelenggaraan pemotongan hewan qurban sapi/kambing secara higienis dan pendistribusian 600 bungkus daging.',
    pic: 'Panitia Qurban DKM',
    allocatedBudget: 8500000,
    targetTimeline: 'Dzulhijjah 1448 H',
    targetDate: '2027-06-05',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 0,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-20',
    notes: 'Program tahunan rutin.',
  },
  {
    id: 'pk-057',
    code: 'PK-ZIS-08',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & ZISWAF',
    seksiId: 'ZISWAF_MUSTAHIQ',
    seksiName: 'Seksi ZISWAF & Pemberdayaan Mustahiq',
    title: 'Bantuan Biaya Pengobatan Darurat Mustahiq Sakit Kritis',
    description: 'Dana taktis pendampingan biaya rawat inap dan obat-obatan yang tidak ditanggung BPJS bagi warga pra-sejahtera.',
    pic: 'Ust. Rahman',
    allocatedBudget: 10000000,
    targetTimeline: 'Sepanjang 2026-2027',
    targetDate: '2026-12-31',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 40,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-03',
    notes: 'Realisasi Rp3.200.000 untuk 3 pasien dhuafa.',
  },

  // ==========================================================================
  // 7. SEKSI PEMBERDAYAAN PEREMPUAN, MAJELIS TAKLIM & TPA (KOMISI PEMBERDAYAAN)
  // ==========================================================================
  {
    id: 'pk-060',
    code: 'PK-PRM-01',
    komisi: 'PEMBERDAYAAN',
    komisiLabel: 'Komisi Pemberdayaan Perempuan & TPA',
    seksiId: 'PEREMPUAN_TPA',
    seksiName: 'Seksi Pemberdayaan Perempuan & TPA',
    title: 'Pengelolaan Operasional TPA Babul Khaer (Iqro & Al-Qur\'an)',
    description: 'Proses belajar mengajar santri TPA setiap hari Senin hingga Kamis ba\'da Ashar di serambi masjid.',
    pic: 'Hj. Rosdiana & Ustadzah Nur',
    allocatedBudget: 21600000,
    targetTimeline: 'Januari - Desember 2026',
    targetDate: '2026-12-31',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 70,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-05',
    notes: 'Membina 48 santri terbagi dalam 3 kelas (Iqro Dasar, Iqro Lanjutan, Al-Qur\'an).',
  },
  {
    id: 'pk-061',
    code: 'PK-PRM-02',
    komisi: 'PEMBERDAYAAN',
    komisiLabel: 'Komisi Pemberdayaan Perempuan & TPA',
    seksiId: 'PEREMPUAN_TPA',
    seksiName: 'Seksi Pemberdayaan Perempuan & TPA',
    title: 'Insentif & Pembinaan Kesejahteraan 4 Ustadzah Pengajar TPA',
    description: 'Penyaluran uang transportasi dan insentif bulanan bagi 4 guru pengajar TPA binaan DKM.',
    pic: 'Hj. Rosdiana',
    allocatedBudget: 14400000,
    targetTimeline: 'Bulanan Tahun 2026',
    targetDate: '2026-12-31',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 65,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-01',
    notes: 'Didukung dari infaq syahriyah bulanan santri dan subsidi kas DKM.',
  },
  {
    id: 'pk-062',
    code: 'PK-PRM-03',
    komisi: 'PEMBERDAYAAN',
    komisiLabel: 'Komisi Pemberdayaan Perempuan & TPA',
    seksiId: 'PEREMPUAN_TPA',
    seksiName: 'Seksi Pemberdayaan Perempuan & TPA',
    title: 'Penyelenggaraan Majelis Taklim Muslimah Pekanan',
    description: 'Kajian fiqih wanita, parenting islami, dan tadarrus Al-Quran khusus ibu-ibu jamaah setiap Sabtu pagi.',
    pic: 'Koordinator Majelis Taklim',
    allocatedBudget: 7200000,
    targetTimeline: 'Sepanjang 2026',
    targetDate: '2026-12-31',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 70,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-03',
    notes: 'Rata-rata kehadiran 50 - 65 jamaah ibu-ibu.',
  },
  {
    id: 'pk-063',
    code: 'PK-PRM-04',
    komisi: 'PEMBERDAYAAN',
    komisiLabel: 'Komisi Pemberdayaan Perempuan & TPA',
    seksiId: 'PEREMPUAN_TPA',
    seksiName: 'Seksi Pemberdayaan Perempuan & TPA',
    title: 'Pengembangan UMKM Gerai Muslimah & Bazar Jumat Berkah',
    description: 'Fasilitasi lapak jualan aneka kuliner halal, jilbab, dan produk binaan jamaah wanita di halaman luar masjid.',
    pic: 'Tim Ekonomi Muslimah',
    allocatedBudget: 8000000,
    targetTimeline: 'Oktober 2026 - Desember 2027',
    targetDate: '2026-10-15',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 40,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-04',
    notes: '12 mitra pedagang muslimah telah mendaftar lapak.',
  },
  {
    id: 'pk-064',
    code: 'PK-PRM-05',
    komisi: 'PEMBERDAYAAN',
    komisiLabel: 'Komisi Pemberdayaan Perempuan & TPA',
    seksiId: 'PEREMPUAN_TPA',
    seksiName: 'Seksi Pemberdayaan Perempuan & TPA',
    title: 'Penyaluran Modal Bergulir Tanpa Riba (Qardhul Hasan) UMKM',
    description: 'Pinjaman modal usaha bergulir Rp 1.000.000 - Rp 2.000.000 bagi 5 pedagang kecil binaan tanpa bunga/bunga 0%.',
    pic: 'H. Sahali & Hj. Rosdiana',
    allocatedBudget: 10000000,
    targetTimeline: 'Mulai November 2026',
    targetDate: '2026-11-20',
    rakerStatus: 'DIREVISI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 20,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-28',
    notes: 'SOP pengembalian cicilan bergulir sedang diverifikasi.',
  },
  {
    id: 'pk-065',
    code: 'PK-PRM-06',
    komisi: 'PEMBERDAYAAN',
    komisiLabel: 'Komisi Pemberdayaan Perempuan & TPA',
    seksiId: 'PEREMPUAN_TPA',
    seksiName: 'Seksi Pemberdayaan Perempuan & TPA',
    title: 'Wisuda Santri TPA Angkatan IX & Munaqasyah Al-Qur\'an',
    description: 'Ujian kelulusan bacaan Al-Quran dan seremoni wisuda bagi 20 santri yang menyelesaikan juz 30.',
    pic: 'Ustadzah Nur & Hj. Rosdiana',
    allocatedBudget: 6500000,
    targetTimeline: 'Maret 2027',
    targetDate: '2027-03-15',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 0,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-20',
    notes: 'Bekerja sama dengan LPPTKA BKPRMI Tamalanrea.',
  },
  {
    id: 'pk-066',
    code: 'PK-PRM-07',
    komisi: 'PEMBERDAYAAN',
    komisiLabel: 'Komisi Pemberdayaan Perempuan & TPA',
    seksiId: 'PEREMPUAN_TPA',
    seksiName: 'Seksi Pemberdayaan Perempuan & TPA',
    title: 'Pelatihan Keterampilan Menjahit & Tata Boga Ibu Jamaah',
    description: 'Kursus singkat membuat kue kering lebaran dan menjahit mukena untuk peningkatan ekonomi keluarga.',
    pic: 'Seksi Pemberdayaan Perempuan',
    allocatedBudget: 5000000,
    targetTimeline: 'Desember 2026',
    targetDate: '2026-12-10',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 0,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-25',
    notes: 'Memanfaatkan aula serbaguna masjid.',
  },
  {
    id: 'pk-067',
    code: 'PK-PRM-08',
    komisi: 'PEMBERDAYAAN',
    komisiLabel: 'Komisi Pemberdayaan Perempuan & TPA',
    seksiId: 'PEREMPUAN_TPA',
    seksiName: 'Seksi Pemberdayaan Perempuan & TPA',
    title: 'Peringatan Hari Ibu & Tabligh Akbar Keutamaan Muslimah',
    description: 'Pengajian akbar akhir tahun menghadirkan penceramah wanita kondang di Sulawesi Selatan.',
    pic: 'Hj. Rosdiana',
    allocatedBudget: 4000000,
    targetTimeline: 'Desember 2026',
    targetDate: '2026-12-22',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BELUM_MULAI',
    progressPercent: 10,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-30',
    notes: 'Panitia gabungan remaja putri dan majelis taklim.',
  },

  // ==========================================================================
  // 8. SEKSI KEAMANAN, KETERTIBAN & LINGKUNGAN
  // ==========================================================================
  {
    id: 'pk-070',
    code: 'PK-KMN-01',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'KEAMANAN_LINGKUNGAN',
    seksiName: 'Seksi Keamanan & Ketertiban Lingkungan',
    title: 'Piket Pengamanan Parkir Kendaraan Sholat Jumat & Tarawih',
    description: 'Pengaturan lalu lintas, penataan saf parkir sepeda motor/mobil, dan pengawasan gerbang utama.',
    pic: 'Koordinator Keamanan & Satpam RW',
    allocatedBudget: 5200000,
    targetTimeline: 'Mingguan Tahun 2026',
    targetDate: '2026-12-31',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 75,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-05',
    notes: 'Alhamdulillah nol insiden kehilangan helm atau kendaraan.',
  },
  {
    id: 'pk-071',
    code: 'PK-KMN-02',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'KEAMANAN_LINGKUNGAN',
    seksiName: 'Seksi Keamanan & Ketertiban Lingkungan',
    title: 'Pengamanan Fisik & Kotak Amal Tromol Masjid (Kunci Dobel)',
    description: 'Pemasangan rantai baja pengaman dan gembok ganda pada seluruh kotak amal tetap dan tromol dorong.',
    pic: 'Koordinator Keamanan',
    allocatedBudget: 1200000,
    targetTimeline: 'Agustus 2026',
    targetDate: '2026-08-20',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'SELESAI',
    progressPercent: 100,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-22',
    notes: 'Semua kotak amal telah dilengkapi kunci ganda berstempel segel.',
  },
  {
    id: 'pk-072',
    code: 'PK-KMN-03',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'KEAMANAN_LINGKUNGAN',
    seksiName: 'Seksi Keamanan & Ketertiban Lingkungan',
    title: 'Penertiban Jadwal Buka-Tutup Pintu Gerbang Malam Hari',
    description: 'Penutupan gerbang utama pukul 22.00 WITA dan pembukaan kembali pukul 03.45 WITA untuk keamanan fasilitas.',
    pic: 'Marbot Firman & Satpam',
    allocatedBudget: 600000,
    targetTimeline: 'Sepanjang 2026-2029',
    targetDate: '2026-12-31',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 90,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-01',
    notes: 'Diterapkan konsisten untuk menghindari penyalahgunaan pelataran.',
  },
  {
    id: 'pk-073',
    code: 'PK-KMN-04',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'KEAMANAN_LINGKUNGAN',
    seksiName: 'Seksi Keamanan & Ketertiban Lingkungan',
    title: 'Pengadaan Alat Pemadam Api Ringan (APAR) 4 Titik',
    description: 'Penyediaan 4 tabung APAR dry chemical 6kg di ruang genset, ruang sound system, dapur, dan sekretariat.',
    pic: 'Bambang Sudarmono',
    allocatedBudget: 3200000,
    targetTimeline: 'Oktober 2026',
    targetDate: '2026-10-25',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 50,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-09-02',
    notes: '2 tabung telah terpasang di ruang genset dan audio.',
  },
  {
    id: 'pk-074',
    code: 'PK-KMN-05',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiId: 'KEAMANAN_LINGKUNGAN',
    seksiName: 'Seksi Keamanan & Ketertiban Lingkungan',
    title: 'Kerja Bakti Massal Kebersihan Lingkungan Masjid Bersama Warga',
    description: 'Pembersihan saluran got, pemangkasan ranting pohon pelataran, dan fogging nyamuk DBD tiap 2 bulan.',
    pic: 'Koordinator Lingkungan & RT',
    allocatedBudget: 3000000,
    targetTimeline: 'Oktober & Desember 2026',
    targetDate: '2026-10-12',
    rakerStatus: 'DISETUJUI',
    executionStatus: 'BERJALAN',
    progressPercent: 30,
    trafficLight: 'HIJAU',
    lastUpdate: '2026-08-25',
    notes: 'Koordinasi bersama pengurus RT 01-05 Blok AE.',
  },
];
