import { RakerBudgetItem, CashflowRunwaySummary } from '@/types/budget';

export const OFFICIAL_RAKER_BUDGETS: RakerBudgetItem[] = [
  // KOMISI I - Peribadatan & Dakwah
  {
    id: 'bg-001',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiName: 'Seksi Peribadatan & Dakwah',
    programName: 'Honorarium Imam Sholat Fardhu (3 Imam Rawatib @ Rp1.5jt/bln)',
    allocatedBudget: 50400000,
    disbursedAmount: 4500000,
    unit: 'Tahun',
    statusRaker: 'DIREVISI',
    fundingSource: 'KAS_MASJID',
    notes: 'Standar baru Rp1.500.000/imam per bulan sesuai usulan Pak Hasri di Raker 2026.',
  },
  {
    id: 'bg-002',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiName: 'Seksi Peribadatan & Dakwah',
    programName: 'Insentif Khatib & Imam Sholat Jumat',
    allocatedBudget: 28800000,
    disbursedAmount: 3000000,
    unit: 'Tahun',
    statusRaker: 'DIREVISI',
    fundingSource: 'KAS_MASJID',
    notes: 'Optimalkan imam rawatib untuk khutbah Jumat, insentif Rp1.500.000.',
  },
  {
    id: 'bg-003',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiName: 'Seksi Peribadatan & Dakwah',
    programName: 'Timer Ampli Otomatis Adzan',
    allocatedBudget: 500000,
    disbursedAmount: 500000,
    unit: 'Kegiatan',
    statusRaker: 'DISETUJUI',
    fundingSource: 'KAS_MASJID',
    notes: 'Telah terpasang untuk ketepatan jadwal kumandang adzan.',
  },
  {
    id: 'bg-004',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiName: 'Seksi Peribadatan & Dakwah',
    programName: 'Kajian/Tabligh Pekanan & Bulanan (Swadaya Jamaah)',
    allocatedBudget: 22800000,
    disbursedAmount: 1800000,
    unit: 'Tahun',
    statusRaker: 'DIREVISI',
    fundingSource: 'SWADAYA_JAMAAH',
    notes: 'Maksimal 2x/pekan, sumber dana swadaya jamaah TIDAK memakai kas masjid.',
  },
  {
    id: 'bg-005',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiName: 'Seksi Peribadatan & Dakwah',
    programName: 'Peringatan Hari Besar Islam (PHBI Maulid & Isra Mi\'raj)',
    allocatedBudget: 3250000,
    disbursedAmount: 0,
    unit: 'Tahun',
    statusRaker: 'DIREVISI',
    fundingSource: 'SWADAYA_JAMAAH',
    notes: 'Dana swadaya jamaah terpisah, satu pintu keluar kas melalui Bendahara Umum (H. Sahali).',
  },
  {
    id: 'bg-006',
    komisi: 'KOMISI_I',
    komisiLabel: 'Komisi I: Peribadatan & Dakwah',
    seksiName: 'Seksi Pendidikan & Remaja',
    programName: 'Pembinaan Remaja Masjid & Pelatihan Leadership',
    allocatedBudget: 15000000,
    disbursedAmount: 0,
    unit: 'Tahun',
    statusRaker: 'DISETUJUI',
    fundingSource: 'KAS_MASJID',
    notes: 'Kebijakan pleno: Tidak boleh ada kotak amal terpisah khusus remaja.',
  },

  // KOMISI II - Pembangunan
  {
    id: 'bg-010',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiName: 'Seksi Pembangunan',
    programName: 'Plafon Masjid Lantai 2',
    allocatedBudget: 350000000,
    disbursedAmount: 0,
    unit: 'Proyek',
    statusRaker: 'DISETUJUI',
    fundingSource: 'DONATUR_KHUSUS',
    notes: 'Proyek renovasi plafon lantai 2 ruang utama sholat.',
  },
  {
    id: 'bg-011',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiName: 'Seksi Pembangunan',
    programName: 'Pembangunan Menara Masjid (Tinggi 30 Meter)',
    allocatedBudget: 1550000000,
    disbursedAmount: 0,
    unit: 'Mega Proyek',
    statusRaker: 'DISETUJUI',
    fundingSource: 'DONATUR_KHUSUS',
    notes: 'Proyek jangka panjang pembangunan ikon menara masjid.',
  },
  {
    id: 'bg-012',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiName: 'Seksi Pembangunan',
    programName: 'Drainase, Pelataran Parkir & Tempat Wudhu Tiap Gerbang',
    allocatedBudget: 150000000,
    disbursedAmount: 0,
    unit: 'Proyek',
    statusRaker: 'DIREVISI',
    fundingSource: 'DONATUR_KHUSUS',
    notes: 'Dikerjakan bertahap mulai pipa pembuangan dan kran air.',
  },
  {
    id: 'bg-013',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiName: 'Seksi Sarana & Prasarana',
    programName: 'Pengadaan AC Duduk Daikin',
    allocatedBudget: 27000000,
    disbursedAmount: 27000000,
    unit: 'Aset Fisik',
    statusRaker: 'DISETUJUI',
    fundingSource: 'KAS_MASJID',
    notes: 'AC duduk standing floor ruang sholat utama telah aktif.',
  },
  {
    id: 'bg-014',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiName: 'Seksi Sarana & Prasarana',
    programName: 'Pemasangan Modul Otomatis & Relokasi Genset Silent',
    allocatedBudget: 3500000,
    disbursedAmount: 850000,
    unit: 'Pemeliharaan',
    statusRaker: 'DIREVISI',
    fundingSource: 'KAS_MASJID',
    notes: 'Genset direlokasi agar tidak bising mengganggu sholat berjamaah.',
  },
  {
    id: 'bg-015',
    komisi: 'KOMISI_II',
    komisiLabel: 'Komisi II: Pembangunan & Sarpras',
    seksiName: 'Seksi Sarana & Prasarana',
    programName: 'Pengadaan 1 Set Komputer & Printer Sekretariat',
    allocatedBudget: 15000000,
    disbursedAmount: 0,
    unit: 'Aset Kantor',
    statusRaker: 'DISETUJUI',
    fundingSource: 'KAS_MASJID',
    notes: 'Peralatan operasional administrasi SIK-MBH dan persuratan dinas.',
  },

  // SOSIAL & HUMAS
  {
    id: 'bg-020',
    komisi: 'SOSIAL_HUMAS',
    komisiLabel: 'Komisi Sosial & UPZ',
    seksiName: 'Seksi Humas & Sosial Kemasyarakatan',
    programName: 'Penerimaan dan Penyaluran ZISWAF Mustahiq RT 01-05',
    allocatedBudget: 30000000,
    disbursedAmount: 12300000,
    unit: 'Tahun',
    statusRaker: 'DISETUJUI',
    fundingSource: 'SWADAYA_JAMAAH',
    notes: 'Digabung dengan program Gerakan Sedekah Seribu Sehari (SSS) dan Panitia UPZ.',
  },
];

export const CURRENT_RUNWAY_METRICS: CashflowRunwaySummary = {
  monthlyOperationalTarget: 10000000, // Rp 10.000.000 / bulan
  weeklyIncomeAverage: 2500000, // Rp 2 - 3 juta per pekan
  currentOperatingCash: 24500000, // Saldo kas operasional saat ini
  runwayMonths: 2.45, // 24.500.000 / 10.000.000 = ~2.4 bulan
  healthStatus: 'WARNING', // Di bawah 3 bulan cadangan
  recommendations: [
    'Catatan Bendahara (H. Sahali): Selisih pengeluaran operasional Rp10 jt/bln vs penerimaan Rp2-3 jt/minggu berisiko defisit bila terjadi lonjakan tagihan listrik/perawatan.',
    'Pertahankan kebijakan satu pintu: Jangan bebani kas operasional untuk kegiatan PHBI, gunakan kas swadaya jamaah.',
    'Optimalkan Program Sedekah Seribu Sehari (SSS) dan Donatur Tetap Bulanan untuk menaikkan rasio kas masuk stabil.',
  ],
};
